### PR TITLE
Magical Zombie Pills place fix

### LINKED ISSUE #2359: Magical Zombie Pills can be placed to soul sand
## :round_pushpin: Description (REQUIRED)

Magical Zombie Pills can be placed to soul sand when right click.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Give Magical Zombie Pills.
2. Right click with Magical Zombie Pills to soul sand.

https://www.youtube.com/watch?v=r55EecFy5zY

## :bulb: Expected behavior (REQUIRED)

Magical Zombie Pills can not placed to soul sand when right click.

## :open_file_folder: /error-reports/ Folder

No error report.

## :compass: Environment (REQUIRED)

 - Server Software (Spigot/Paper): Paper
 - Minecraft Version: 1.16.3
 - Slimefun Version: vDEV - 685 (git dc551907)
 - CS-CoreLib Version: vDEV - 91 (git e42a05d1)

### PR DESCRIPTION
**Pull request by poma123**
## Description

Added a cancelled ItemUseHandler to prevent placing Magical Zombie Pills.

## Changes

Added a cancelled ItemUseHandler.

## Related Issues

Fixes #2359 

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/MagicalZombiePills.java [hunk 1]
```diff
@@ -61,4 +65,7 @@ public EntityInteractHandler getItemHandler() {
         };
     }
 
+    public ItemUseHandler onRightClick() {
+        return PlayerRightClickEvent::cancel;
+    }
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/MagicalZombiePills.java:70]: Mind adding a docs tag to that method to explain why it's cancelled?
For future reference in case someone stumbles across this and gets confused

Comment (poma123) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/MagicalZombiePills.java:70]: Like this?
```suggestion
    /**
     * This method cancels {@link PlayerRightClickEvent} to prevent placing Magical Zombie Pills.
     */
    public ItemUseHandler onRightClick() {
        return PlayerRightClickEvent::cancel;
    }
```

Comment (TheBusyBiscuit) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/MagicalZombiePills.java:70]: Yeah, but you forgot the `@return` tag and you could make "Magical Zombie Pills" an `@link` too :)

**Review by TheBusyBiscuit — CHANGES_REQUESTED** [review]
Oh one thing I forgot: The class should probably also implement `NotPlaceable` after this change too

**Review by TheBusyBiscuit — APPROVED** [review]
LGTM

Side note: I love the new "Teams" mechanic for the organization

**Review by TheBusyBiscuit — APPROVED** [review]
Dismissed my previous review :NotLikeThis:

**Comment by poma123** [comment]
> Dismissed my previous review :NotLikeThis:

Missed the wrong location of that ugly import :NotLikeThis:

**Review by LinoxGH — APPROVED** [review]
