### PR TITLE
Fixes #3248

### LINKED ISSUE #3248: AutoEnchanter overrides enchantments
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Auto Enchanter overrides lower level on the same enchantment
Example: Pickaxe already have Unbreaking 10 and you add Unbreaking 3 book, you will get Unbreaking 3 on the final product

https://discord.com/channels/565557184348422174/565569972697301020/886602517071425637

### 📑 Reproduction Steps

1. Use auto enchanter
2. Put higher level enchantment on the main item
3. Put lower level enchantment on enchanted book
4. Lower level overrides the higher level

### 💡 Expected Behavior

Auto Enchanter should keep the highest level enchantments

### 📷 Screenshots / Videos

https://youtu.be/MXJ_LuQxJFs

### 📜 Server Log

_No response_

### 📂 `/error-reports/` folder

_No response_

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.17.x

### ⭐ Slimefun version

```
> sf versions
[21:07:57 INFO]: This Server uses the following setup of Slimefun:
Paper git-Paper-259 (MC: 1.17.1)
Slimefun DEV - 968 (git 79c6c139)
Metrics-Module #28
Java 16

No Addons installed
> pl
[21:07:57 INFO]: Plugins (3): Slimefun, Vault, VoidGen
> ver
[21:07:58 INFO]: Checking version, please wait...
[21:08:00 INFO]: This server is running Paper version git-Paper-259 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 810d200)
You are running the latest version
Previous version: git-Paper-250 (MC: 1.17.1)
```

### 🧭 Other plugins

_No response_

### PR DESCRIPTION
**Pull request by Sfiguz7**
## Description

As of now, the AutoEnchanters blindly apply whatever is on the enchanted book onto the item, disregarding any check other than compatibility ones.
A small discussion on the Discord lead to two main ideas: some people like the fact everything gets overridden, meaning an extra layer of difficulty is added as more thought and planning has to be put in instead of blindly slapping books on the item. On the other hand, some people like the idea of the enchanter not completely disregarding what is on the item to begin with, and it to be able to only update the enchantments it needs to.

This PR is motivated by this dichotomy: an additional item setting has been added that allows servers to choose whether they do want the override or not (defaulting to yes so that the old behavior is conserved). If the enchantment to be applied is of lower or equal level it is ignored meaning the enchanting time is also reduced.

## Proposed changes

Added itemSetting to AutoEnchanters to choose whether existing enchants should be overridden no matter what or checked for an improvement first. Defaults to old behavior for consistency.

TESTING SAMPLE:
Sword and book used
https://imgur.com/a/Q1k7tK0

Time and result with setting to true (default):
https://imgur.com/a/dVjzpCX

Time and result with setting to false (new behavior):
https://imgur.com/a/RetSUwJ

## Related Issues (if applicable)

Resolves #3248 

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

**Comment by svr333** [comment]
Uh #3255

**Comment by Sfiguz7** [comment]
Ah you had done it already. Hmm I don't know if it should be a setting or just default, I don't mind either way. I will keep this open so we can choose which one to actually merge

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoEnchanter.java [hunk 1]
```diff
@@ -6,6 +6,7 @@
 import javax.annotation.Nullable;
 import javax.annotation.ParametersAreNonnullByDefault;
 
+import io.github.thebusybiscuit.slimefun4.api.items.ItemSetting;
```
Comment (ybw0014) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoEnchanter.java:9]: this import should not be here

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoEnchanter.java [hunk 2]
```diff
@@ -103,6 +108,12 @@ protected MachineRecipe enchant(BlockMenu menu, ItemStack target, ItemStack ench
             }
         }
 
+        // If override is false, remove those with lower level so we don't override existing enchants
+        // This also removes those with the same level so they aren't accounted for enchanting time
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoEnchanter.java:112]: Multiline comments exist.

**Comment by Sfiguz7** [comment]
We should decide whether we want it to be optional (this PR) or permanent (#3255) before I fix the two things. Shall we have a chat in #developers?

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoEnchanter.java [hunk 3]
```diff
@@ -39,9 +40,13 @@
  */
 public class AutoEnchanter extends AbstractEnchantmentMachine {
 
+    private final ItemSetting<Boolean> overrideExistingEnchantsLvl= new ItemSetting<>(this, "override-existing-enchants-lvl", true);
```
Comment (svr333) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoEnchanter.java:43]:
```suggestion
    private final ItemSetting<Boolean> overrideExistingEnchantsLvl= new ItemSetting<>(this, "override-existing-enchants-lvl", false);
```

**Review by svr333 — CHANGES_REQUESTED** [review]

**Comment by Sfiguz7** [comment]
For those with access, the discussion took place [here](https://discord.com/channels/565557184348422174/565570276038017044/888122263872872498) (just in case, for future reference)

**Review by svr333 — APPROVED** [review]

**Review by TheBusyBiscuit — APPROVED** [review]
lgtm
