### PR TITLE
Fix pedestal item disappearing

### LINKED ISSUE #3476: Item disappears when taking item back on pedestal while inventory is full.
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When inventory is full and you take something on the pedestal, the item will disappear.

### 📑 Reproduction Steps

1. place pedestal
2. put an item on it
3. make inventory full
4. take out the item on the pedestal

### 💡 Expected Behavior

The item will not able to be taken/ dropped on the ground

### 📷 Screenshots / Videos

_No response_

### 📜 Server Log

_No response_

### 📂 `/error-reports/` folder

_No response_

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.18.x

### ⭐ Slimefun version

image
image
image
image

### 🧭 Other plugins

_No response_

### PR DESCRIPTION
**Pull request by FN-FAL113**
## Description
A small bug fix for the ancient pedestal when retrieving placed items.

## Proposed changes
- Drop item instead if the player's inventory is full and no remaining stack space when retrieving the item back from the pedestal

## Related Issues (if applicable)
- Resolves #3476 

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/AncientAltarListener.java [hunk 1]
```diff
@@ -156,8 +156,18 @@ private void usePedestal(@Nonnull Block pedestal, @Nonnull Player p) {
...
             entity.remove();
-            p.getInventory().addItem(pedestalItem.getOriginalItemStack(entity));
             p.playSound(pedestal.getLocation(), Sound.ENTITY_ITEM_PICKUP, 1F, 1F);
+
+            /*
+             * Fixes #3476
+             * Drop the item instead if the player's
+             * inventory is full
+             */
+            if (p.getInventory().firstEmpty() != -1) {
```
Comment (Sefiraat) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/AncientAltarListener.java:166]: This will not check if the item actually fits in the target inventory. Best to add the items but then check the returned Map<Integer, ItemStack> and drop what if left behind. This way item retrieval will work with a full inventory but with space in a stack for the item being removed

Comment (FN-FAL113) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/AncientAltarListener.java:166]: It does add stacked items to another stacked ones but does this imply It must drop the remaining items that cannot be stacked onto other items anymore?

Comment (FN-FAL113) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/AncientAltarListener.java:166]: The pedestal only accepts one item at a time though and do not support placing stacked items, I could just get the returned map assign it to a variable and for each value is gonna be dropped

Comment (FN-FAL113) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/AncientAltarListener.java]: Very well, it makes it much simple and since the pedestal only supports one amount of  placed item at a time and it can only return a single amount item

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/AncientAltarListener.java [hunk 2]
```diff
@@ -156,8 +156,18 @@ private void usePedestal(@Nonnull Block pedestal, @Nonnull Player p) {
...
             entity.remove();
-            p.getInventory().addItem(pedestalItem.getOriginalItemStack(entity));
             p.playSound(pedestal.getLocation(), Sound.ENTITY_ITEM_PICKUP, 1F, 1F);
+
+            /*
+             * Fixes #3476
+             * Drop the item instead if the player's inventory is full and
+             * no stack space left else add the item in the inventory
+             */
+            for (Map.Entry<Integer, ItemStack> stackEntry : p.getInventory().addItem(pedestalItem.getOriginalItemStack(entity)).entrySet()) {
```
Comment (Sefiraat) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/AncientAltarListener.java:166]: I think declaring the map separately from the for loop here would be far easier to read and far neater.

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/AncientAltarListener.java [hunk 3]
```diff
@@ -156,8 +156,18 @@ private void usePedestal(@Nonnull Block pedestal, @Nonnull Player p) {
...
+                if (stackEntry != null) {
```
Comment (Sefiraat) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/AncientAltarListener.java:167]: I’m fairly sure when iterating the entry set you can’t get a nullable entry? Could be wrong as I’m not at my desk but I feel like this isn’t needed?

Comment (Sefiraat) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/AncientAltarListener.java:167]: Also, may just be best to iterate the values directly, don’t think the int it required in this context at all.

Comment (FN-FAL113) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/AncientAltarListener.java:167]: > I’m fairly sure when iterating the entry set you can’t get a nullable entry? Could be wrong as I’m not at my desk but I feel like this isn’t needed?
Yes thats correct, I added it for debugging and safety ig when I was testing it ingame, I can fully remove it in the next commit

**Review by Sefiraat — APPROVED** [review]
Looks fine to me :)

**Comment by FN-FAL113** [comment]
Oh this should be missing some imports will fix later

**Review by Sefiraat — APPROVED** [review]
Looks good to me :)
