### PR TITLE
Cartography Table fix

### LINKED ISSUE #2357: Paper items can be used in Cartography table for maps
## :round_pushpin: Description (REQUIRED)

Bandage, rag, Reinforced Cloth, Plastic Sheet, Steel plate, Cloth, Reinforced Plate and Magical Book Cover, Scroll of Dimensional Teleposition can be used in Cartography table for maps.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Give a Slimefun Paper item.
2. Can be craft maps in Cartography table from Paper items.

Bandage
Rag

## :bulb: Expected behavior (REQUIRED)

Can not craft maps in Cartography table from Slimefun Paper items.

## :open_file_folder: /error-reports/ Folder

No error report.

## :compass: Environment (REQUIRED)

 - Server Software (Spigot/Paper): Paper
 - Minecraft Version: 1.16.3
 - Slimefun Version: vDEV - 685 (git dc551907)
 - CS-CoreLib Version: vDEV - 91 (git e42a05d1)

### PR DESCRIPTION
**Pull request by poma123**
## Description

Added an EventHandler to `VanillaMachinesListener` class to prevent Slimefun items from being used in Cartography Tables.

## Changes

- Added `onCartographyTable()` EventHandler to `VanillaMachinesListener` class
- Added Unit Tests
- Added `cartography_table.not-working` message to `messages_en.yml`

## Related Issues

Fixes #2357 

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [x] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/VanillaMachinesListener.java [hunk 1]
```diff
@@ -97,6 +97,19 @@ public void onAnvil(InventoryClickEvent e) {
         }
     }
 
+    @EventHandler(ignoreCancelled = true)
+    public void onCartographyTable(InventoryClickEvent e) {
+        if (e.getRawSlot() == 2 && e.getInventory().getType() == InventoryType.CARTOGRAPHY && e.getWhoClicked() instanceof Player) {
```
Comment (LinoxGH) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/VanillaMachinesListener.java:102]: I think this is a bit too long of an if statement.

File: src/main/resources/languages/messages_en.yml [hunk 2]
```diff
@@ -264,6 +264,9 @@ anvil:
 brewing_stand:
   not-working: '&4You cannot use Slimefun Items in a brewing stand!'
 
+cartography_table:
+  not-working: '&4You cannot use Slimefun Items in a cartography table!'
```
Comment (LinoxGH) [inline src/main/resources/languages/messages_en.yml:268]: Why is `I` in here capitalized?

**Review by LinoxGH — CHANGES_REQUESTED** [review]

**Review by LinoxGH — DISMISSED** [review]

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/VanillaMachinesListener.java [hunk 3]
```diff
@@ -97,6 +97,20 @@ public void onAnvil(InventoryClickEvent e) {
         }
     }
 
+    @EventHandler(ignoreCancelled = true)
+    public void onCartographyTable(InventoryClickEvent e) {
+        if (e.getRawSlot() == 2 && e.getInventory().getType() == InventoryType.CARTOGRAPHY
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/VanillaMachinesListener.java:102]: The Cartography table doesn't exist in 1.13 I think, so this will require a version check here

**Review by TheBusyBiscuit — CHANGES_REQUESTED** [review]
One small mistake, otherwise looking great!

**Review by LinoxGH — APPROVED** [review]
LGTM although it could be improved by separating the if statement into 2 or 3 if statements.

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/VanillaMachinesListener.java [hunk 4]
```diff
@@ -97,6 +97,20 @@ public void onAnvil(InventoryClickEvent e) {
         }
     }
 
+    @EventHandler(ignoreCancelled = true)
+    public void onCartographyTable(InventoryClickEvent e) {
+        if (SlimefunPlugin.getMinecraftVersion().isAtLeast(MinecraftVersion.MINECRAFT_1_14) && e.getRawSlot() == 2
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/VanillaMachinesListener.java:102]: You should probably format it like it was done with the Grindstone here:
https://github.com/Slimefun/Slimefun4/pull/2377/files#diff-1d5c31c48a96cc8f0cfae3f72789abd9R43-R47
Because I think a comment explaining why we abort on earlier versions is important to keep there.

**Review by TheBusyBiscuit — CHANGES_REQUESTED** [review]

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/VanillaMachinesListener.java (hunk 4 above)
Comment (poma123) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/VanillaMachinesListener.java:102]: Okay

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/VanillaMachinesListener.java [hunk 5]
```diff
@@ -97,6 +97,25 @@ public void onAnvil(InventoryClickEvent e) {
         }
     }
 
+    @EventHandler(ignoreCancelled = true)
+    public void onCartographyTable(InventoryClickEvent e) {
+        // The Cartography Table was only ever added in MC 1.14
+        MinecraftVersion minecraftVersion = SlimefunPlugin.getMinecraftVersion();
```
Comment (LinoxGH) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/VanillaMachinesListener.java:103]: Why do you create a variable here? This just creates an unnecessary memory heap for gc to clean.

**Review by LinoxGH — CHANGES_REQUESTED** [review]

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/VanillaMachinesListener.java [hunk 6]
```diff
@@ -97,6 +97,25 @@ public void onAnvil(InventoryClickEvent e) {
...
+        if (!minecraftVersion.isAtLeast(MinecraftVersion.MINECRAFT_1_14)) {
```
Comment (LinoxGH) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/VanillaMachinesListener.java:104]:
```suggestion
        if (!SlimefunPlugin.getMinecraftVersion().isAtLeast(MinecraftVersion.MINECRAFT_1_14)) {
```
This should suffice.

**Review by LinoxGH — CHANGES_REQUESTED** [review]

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/VanillaMachinesListener.java (hunk 5 above)
Comment (poma123) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/VanillaMachinesListener.java]: There you go.

**Review by LinoxGH — APPROVED** [review]

**Review by TheBusyBiscuit — APPROVED** [review]
