### PR TITLE
Fixes #3265

### LINKED ISSUE #3265: Backpack Deletion Bug
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

I have encountered a bug that makes a backpack eat itself up and delete it forever.

### 📑 Reproduction Steps

1. Open a backpack in your offhand
2. Press F or your offhand key while hovering over a slot in the opened backpack
3. Close out of backpack
4. Boom the backpack is gone forever

### 💡 Expected Behavior

I didn't know what I expected to happen, I was trying to see if I could put backpacks in backpacks that way I guess

### 📷 Screenshots / Videos
image_2021-09-17_091907

### 📜 Server Log

I don't have access to server logs

### 📂 `/error-reports/` folder

I don't have access to server folders

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.17.x

### ⭐ Slimefun version

DEV - 937

### 🧭 Other plugins

None

### PR DESCRIPTION
**Pull request by variananora**
## Description

You can bypass the item check by using off hand swap
Also idk where to add the comment on 'Fixes xxxx' thing

## Proposed changes

Added checks for off hand item

## Related Issues (if applicable)

Fixes #3265

## Checklist

- [X] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [X] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BackpackListener.java [hunk 1]
```diff
@@ -103,6 +103,14 @@ public void onClick(InventoryClickEvent e) {
...
                         }
                     }
+                } else if (e.getClick() == ClickType.SWAP_OFFHAND) { // Fixes #3265
+                    if (e.getClickedInventory().getType() != InventoryType.PLAYER) {
+                        ItemStack offHandItem = e.getWhoClicked().getInventory().getItemInOffHand();
+
+                        if (!isAllowed((SlimefunBackpack) backpack, offHandItem)) {
+                            e.setCancelled(true);
+                        }
+                    }
```
Comment (WalshyDev) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BackpackListener.java:113]: Should this just always be cancelled? From what I can tell that isAllowed will be true still for the reported issue. Relevant code: https://github.com/Slimefun/Slimefun4/blob/eec5d2d66b2185b60c8eb34b293a9f8d78b6078a/src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BackpackListener.java#L121-L127

```suggestion
                } else if (e.getClick() == ClickType.SWAP_OFFHAND && e.getClickedInventory().getType() != InventoryType.PLAYER) {
                    // Fixes #3265
                    ItemStack offHandItem = e.getWhoClicked().getInventory().getItemInOffHand();

                    if (!isAllowed((SlimefunBackpack) backpack, offHandItem)) {
                        e.setCancelled(true);
                    }
```

**Review by WalshyDev — CHANGES_REQUESTED** [review]

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BackpackListener.java (hunk 1 above)
Comment (WalshyDev) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BackpackListener.java:113]: Oh wait I see, the item will be the backpack which isn't allowed. Me dumb

**Review by svr333 — APPROVED** [review]
LGTM

**Review by WalshyDev — APPROVED** [review]
