### PR TITLE
Refactoring + Fixes to Block Handlers

### LINKED ISSUE #2560: Breaking Infused Hoppers with a hopper limitation applied doesn't subtract them from the hopper limit.
## :round_pushpin: Description (REQUIRED)

Placing an infused hopper down with a hopper limitation applied and then breaking said hopper will still count towards the hopper limitation. So if you for example have 1 hopper as a limit and you place down 1 infused hopper, then break the hopper, you can no longer place any other hoppers down. This only seems to happen with the infused hopper, regular hoppers and hoppers from other plugins work fine.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

Set a hopper limit (Preferably 1 for easier testing).
Get an infused hopper and place it down.
Break infused hopper.
Try to place another hopper down (any) and it will tell you it's not possible.

## :bulb: Expected behavior (REQUIRED)

Breaking the infused hopper should no longer count towards the limit.

## :scroll: Server Log

No errors but still got a link for you anyway:
https://pastebin.com/sFFGHfv3

## :open_file_folder: /error-reports/ Folder

The latest one was october 25th (Nearly a month ago) I figure you don't want those error reports
https://i.imgur.com/RPjcwgc.png

## :compass: Environment (REQUIRED)

I can't include it all in one screenshot so I split it in two with the last line being the first in the second:
https://i.imgur.com/v3IXQ2z.png
https://i.imgur.com/ODLFSO9.png

 - Server Software (Spigot/Paper): Yatopia
 - Minecraft Version: 1.16.4
 - Slimefun Version: vDEV - 744
 - CS-CoreLib Version: vDEV - 90

### PR DESCRIPTION
**Pull request by TheBusyBiscuit**
## Description

This Pull Request is meant to replace the old `SlimefunBlockHandler` in the future.
Slimefun has been using an `ItemHandler`-based system for quite some time now and block-breaking should finally be transferred over.
This will also fix two bugs.

## Related Issues

* Resolves #2560 

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/MiningAndroidListener.java [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+import me.mrCookieSlime.Slimefun.api.BlockStorage;
+
+public class MiningAndroidListener implements Listener {
+
+    public MiningAndroidListener(@Nonnull SlimefunPlugin plugin) {
+        plugin.getServer().getPluginManager().registerEvents(this, plugin);
+    }
+
+    @EventHandler(ignoreCancelled = true)
+    public void onEntityExplode(AndroidMineEvent e) {
```
Comment (Sfiguz7) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/MiningAndroidListener.java:21]: Miners using dynamite :p

**Review by Sfiguz7 — APPROVED** [review]
Loots of annotation to go through, had to double check as I was getting deja vu's ahaha
This will need changes in places for most Addons but it does make sense to move on; couldn't spot anything much (other than the method name for androids) so I'll approve this

EDIT: if you want to send me a Jar with the changes I can test it on our Dev server, it has a bunch of Addons and one of the skyblock hopper limits so it could be a decent test, definitely better than no test at all

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/MiningAndroidListener.java (hunk 1 above)
Comment (TheBusyBiscuit) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/MiningAndroidListener.java:21]: whooooops XD

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/blocks/HologramProjector.java [hunk 2]
```diff
@@ -51,13 +60,28 @@ public void onPlayerPlace(BlockPlaceEvent e) {
...
+            @Override
+            public void onExplode(Block b, List<ItemStack> drops) {
+                remove(b);
+            }
+
+            @Override
+            public void onAndroidBreak(AndroidMineEvent e) {
+                remove(e.getBlock());
+            }
         };
```
Comment (WalshyDev) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/blocks/HologramProjector.java:81]:
```suggestion
        return new SimpleBlockBreakHandler() {

            @Override
            public void onBlockBreaking(@Nonnull Block b) {
                remove(b);
            }
        };
```

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/handlers/SimpleBlockBreakHandler.java [hunk 3]
```diff
@@ -0,0 +1,59 @@
...
+    }
+
+    /**
+     * This method is called when a {@link Block} of this type is broken by a {@link Player},
+     * by a {@link MinerAndroid} or through an explosion.
+     * 
+     * @param b
+     *            The broken {@link Block}
+     */
+    public abstract void onBlockBreaking(@Nonnull Block b);
```
Comment (WalshyDev) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/handlers/SimpleBlockBreakHandler.java:42]: should be called onBlockBreak

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/blocks/HologramProjector.java [hunk 4]
```diff
@@ -51,13 +60,28 @@ public void onPlayerPlace(BlockPlaceEvent e) {
...
     }
 
+    @Nonnull
     private BlockBreakHandler onBreak() {
-        return (e, item, fortune, drops) -> {
-            remove(e.getBlock());
-            return true;
+        return new BlockBreakHandler(true, true) {
```
Comment (WalshyDev) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/blocks/HologramProjector.java:65]: Can just use SimpleBlockBreakHandler here

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/ExplosionsListener.java [hunk 5]
```diff
@@ -41,6 +64,24 @@ public void onEntityExplode(EntityExplodeEvent e) {
...
+                        item.callItemHandler(BlockBreakHandler.class, handler -> {
+                            if (handler.isExplosionAllowed()) {
+                                BlockStorage.clearBlockInfo(block);
+                                block.setType(Material.AIR);
+
+                                List<ItemStack> drops = new ArrayList<>();
+                                handler.onExplode(block, drops);
+
+                                for (ItemStack drop : drops) {
+                                    if (drop != null && drop.getType() != Material.AIR) {
```
Comment (WalshyDev) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/ExplosionsListener.java:77]: should use isAir, if we're doing an air check may as well make it future proof. Who knows what MC, Spigot or other plugins will do

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/ExplosionsListener.java [hunk 6]
```diff
@@ -41,6 +64,24 @@ public void onEntityExplode(EntityExplodeEvent e) {
...
                     if (blockHandler != null) {
                         success = blockHandler.onBreak(null, block, item, UnregisterReason.EXPLODE);
+                    } else {
+                        item.callItemHandler(BlockBreakHandler.class, handler -> {
+                            if (handler.isExplosionAllowed()) {
+                                BlockStorage.clearBlockInfo(block);
+                                block.setType(Material.AIR);
+
+                                List<ItemStack> drops = new ArrayList<>();
+                                handler.onExplode(block, drops);
```
Comment (WalshyDev) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/ExplosionsListener.java:74]: would be great if we could cancel without disabling all explosions. If we had the event we could cancel and then check if cancelled above.

Would be nice for cases like, block durability (for like factions), allows explosion if out of electricity, etc.

**Review by WalshyDev — CHANGES_REQUESTED** [review]
Looking good, a few things I've seen

**Review by Sfiguz7 — APPROVED** [review]

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/ExplosionsListener.java (hunk 6 above)
Comment (TheBusyBiscuit) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/ExplosionsListener.java:74]: I added a Block param to the `isExplosionAllowed` method, it will be ignored by default but if you were to implement sth like that, you could override the method and handle durability there.

**Review by WalshyDev — APPROVED** [review]
LGTM

**Review by WalshyDev — APPROVED** [review]
LGTM

Sorry for the long review time on this 😅

**Review by WalshyDev — APPROVED** [review]
LGTM

**Comment by Phoenix-Starlight** [comment]
> 
> 
> Loots of annotation to go through, had to double check as I was getting deja vu's ahaha
> This will need changes in places for most Addons but it does make sense to move on; couldn't spot anything much (other than the method name for androids) so I'll approve this
> 
> EDIT: if you want to send me a Jar with the changes I can test it on our Dev server, it has a bunch of Addons and one of the skyblock hopper limits so it could be a decent test, definitely better than no test at all

Kinda late for me to say something, but here is a jar if you want to test. (If you already have one, no big deal, just ignore this.)
[Slimefun v4.9-UNOFFICIAL.zip](https://github.com/Slimefun/Slimefun4/files/6012585/Slimefun.v4.9-UNOFFICIAL.zip)

**Review by Sfiguz7 — APPROVED** [review]
Sorry for the long wait, I'm back! LGTM
