### PR TITLE
Nether Goo "Tainted Sheep"

### LINKED ISSUE #2414: Strange Nether Goo can be used to dye sheep
## :round_pushpin: Description (REQUIRED)

Since the Nether Goo is actually purple dye, it can be used to dye sheeps.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Get Strange Nether Goo
2. Find a Sheep
3. Right-Click said Sheep with the Nether Goo
4. Watch the Sheep turn purple

## :bulb: Expected behavior (REQUIRED)

Here I would have two proposed solutions.

#### 1. Cancelling the event
Simply stop sheep from being dyed by strange nether goo, like an Entity handler for the Strange Nether Goo item that just cancels the event

#### 2. NETHER GOO SHEEPS
How about adding a handler but instead of cancelling it, let the sheep go purple and give it poison or a name and whatever XD
Like a tainted sheep.

## :scroll: Server Log

*Nope*

## :open_file_folder: /error-reports/ Folder

*Nope*

## :compass: Environment (REQUIRED)

 - Server Software (Spigot/Paper): Paper
 - Minecraft Version: 1.16.3
 - Slimefun Version:  DEV 708
 - CS-CoreLib Version: DEV 91

### PR DESCRIPTION
**Pull request by CURVX**
## Description

Nether Goo now changes an ordinary sheep to **Tainted Sheep**.
- When applied to a Sheep without a CustomName, it renames that Sheep to **Tainted Sheep**.
- Changes wool color to **PURPLE**.
- Gets poisoned for 3 seconds with _Poison PotionEffect II_.

## Changes

Added `addItemHandler(onRightClickEntity())`

## Related Issues

Resolves #2414

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

**Comment by LinoxGH** [comment]
I think this shouldn't be possible if the sheep has a custom name.

**Comment by CURVX** [comment]
> 
> 
> I think this shouldn't be possible if the sheep has a custom name.

If I nametag a sheep, and then apply the Nether Goo, it changes its name to **Tainted Sheep**. I think I got the term wrong with CustomName 😕

**Comment by LinoxGH** [comment]
> > 
> > 
> > I think this shouldn't be possible if the sheep has a custom name.
> 
> If I nametag a sheep, and then apply the Nether Goo, it changes its name to **Tainted Sheep**. I think I got the term wrong with CustomName 😕   
> 

Yes if the sheep has a custom name, the items shouldn't work. That's what I think.

**Comment by LinoxGH** [comment]
> > 
> > 
> > I think this shouldn't be possible if the sheep has a custom name.
> 
> If I nametag a sheep, and then apply the Nether Goo, it changes its name to **Tainted Sheep**. I think I got the term wrong with CustomName 😕   
> 

Yes if the sheep has a custom name, the items shouldn't work. That's what I think.

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/misc/StrangeNetherGoo.java [hunk 1]
```diff
@@ -56,4 +66,28 @@ public ItemUseHandler getItemHandler() {
...
 
+    private EntityInteractHandler onRightClickEntity() {
+        return (e, item, hand) -> {
+            if ((e.getRightClicked() instanceof Sheep) && (e.getRightClicked() instanceof LivingEntity)) {
+                Sheep s = (Sheep) e.getRightClicked();
+
+                if (s.getCustomName() != null) {
+                    if (s.getCustomName().equals(ChatColor.DARK_PURPLE+"Tainted Sheep") && s.getColor() == DyeColor.PURPLE) {
+                        return;
+                    }
```
[the remark this answers is not in the document]
Comment (CURVX) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/misc/StrangeNetherGoo.java:77]: Oh, now I understand. 👍

[the remark this answers is not in the document]
Comment (CURVX) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/misc/StrangeNetherGoo.java:77]: If commit directly as suggested from here, will this mess up formatting ?

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/misc/StrangeNetherGoo.java [hunk 2]
```diff
@@ -56,4 +66,26 @@ public ItemUseHandler getItemHandler() {
         };
     }
 
+    private EntityInteractHandler onRightClickEntity() {
+        return (e, item, hand) -> {
+            if ((e.getRightClicked() instanceof Sheep) && (e.getRightClicked() instanceof LivingEntity)) {
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/misc/StrangeNetherGoo.java:71]: This is redundant, a Sheep is an extension of a LivingEntity, therefore if something is a Sheep, it's also a LivingEntity.

```suggestion
            if (e.getRightClicked() instanceof Sheep) {
```

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/misc/StrangeNetherGoo.java [hunk 3]
```diff
@@ -56,4 +66,26 @@ public ItemUseHandler getItemHandler() {
...
+                Sheep s = (Sheep) e.getRightClicked();
+
+                if (s.getCustomName() != null) {
+                    return;
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/misc/StrangeNetherGoo.java:75]: You should probably cancel the event here too to prevent them from dying the sheep.

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/misc/StrangeNetherGoo.java [hunk 4]
```diff
@@ -56,4 +66,26 @@ public ItemUseHandler getItemHandler() {
...
+                }
+
+                if (e.getPlayer().getGameMode() != GameMode.CREATIVE) {
+                    ItemUtils.consumeItem(item, false);
+                }
+
+                // Give Sheep color, name and effect
+                s.addPotionEffect(new PotionEffect(PotionEffectType.POISON, 60, 2));
+                s.setColor(DyeColor.PURPLE);
+                s.setCustomName(ChatColor.DARK_PURPLE+"Tainted Sheep");
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/misc/StrangeNetherGoo.java:85]: Formatting.
```suggestion
                s.setCustomName(ChatColor.DARK_PURPLE + "Tainted Sheep");
```

**Review by TheBusyBiscuit — CHANGES_REQUESTED** [review]
A few small requests but I am liking this a lot so far!

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/misc/StrangeNetherGoo.java (hunk 2 above)
Comment (CURVX) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/misc/StrangeNetherGoo.java]: Was right there `Methods inherited from interface org.bukkit.entity.LivingEntity`. I need to learn how to use Javadocs :D

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/misc/StrangeNetherGoo.java [hunk 5]
```diff
@@ -56,4 +65,27 @@ public ItemUseHandler getItemHandler() {
         };
     }
 
+    private EntityInteractHandler onRightClickEntity() {
+        return (e, item, hand) -> {
+            if ((e.getRightClicked() instanceof Sheep)) {
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/misc/StrangeNetherGoo.java:70]: Redundant brackets :eyes:
```suggestion
            if (e.getRightClicked() instanceof Sheep) {
```

**Review by TheBusyBiscuit — CHANGES_REQUESTED** [review]

**Review by TheBusyBiscuit — APPROVED** [review]
LGTM
