### PR TITLE
Patch for #3922

### LINKED ISSUE #3922: Ancient Pedestal not working in 1.17.1 and below
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Using the latest dev after #3784 merge, ancient pedestal won't work in 1.17.1 and below because it's doesn't have `setUnlimitedLifetime(boolean)` method under the `org.bukkit.entity.Item` class.

### 📑 Reproduction Steps

1. use minecraft 1.17.1 or older
2. place an ancient pedestal
3. right click the ancient pedestal with an item
4. the item will just pops right back

### 💡 Expected Behavior

The item should stay hovering on top of the ancient pedestal

### 📷 Screenshots / Videos

_No response_

### 📜 Server Log

https://pastebin.com/xVvNCx2Z

### 📂 `/error-reports/` folder

_No response_

### 💻 Server Software

Spigot

### 🎮 Minecraft Version

1.17.x

### ⭐ Slimefun version

image

### 🧭 Other plugins

_No response_

### PR DESCRIPTION
**Pull request by JustAHuman-xD**
## Description
Making this PR to remove a version dependent method that was missed with the ancient altar fix PR

## Proposed changes
Resolves #3922 

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I have made sure that the proposed changes do not break compatibility across the supported Minecraft versions (1.16.* - 1.20.*).
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/AncientAltarListener.java [hunk 1]
```diff
@@ -357,4 +358,11 @@ public void onBlockPlace(BlockPlaceEvent e) {
         return Optional.empty();
     }
 
+    @EventHandler(priority = EventPriority.LOW, ignoreCancelled = true)
+    public void onItemDespawn(ItemDespawnEvent e) {
+        if (AncientPedestal.testItem(e.getEntity())) {
+            e.setCancelled(true);
+        }
+    }
+
```
Comment (variananora) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/AncientAltarListener.java:367]:
```suggestion
```

**Comment by variananora** [comment]
Tested in both 1.16.5 and 1.20.1.

**Comment by JustAHuman-xD** [comment]
> Tested in both 1.16.5 and 1.20.1.

Did you test if this did properly stop the items from despawning? Or just that it didn't error.

**Comment by variananora** [comment]
> Did you test if this did properly stop the items from despawning? Or just that it didn't error.

Sorry for the lack of info, yeah I tested both that it didn't error and it didn't despawn.

**Comment by JustAHuman-xD** [comment]
> Sorry for the lack of info, yeah I tested both that it didn't error and it didn't despawn.

Awesome and np! Just wanted to check is all, thank you for testing so quickly!

**Review by J3fftw1 — DISMISSED** [review]

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/AncientAltarListener.java (hunk 1 above)
Comment (JustAHuman-xD) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/AncientAltarListener.java:367]: I honestly left it because I wasn't sure which way fit the code style. A lot of classes have an empty line before the closing bracket and a lot also don't, this one did before hand so I left it

**Review by Sefiraat — APPROVED** [review]
Looking fine and big thanks to Var for doing the long testing :) <3

**Review by variananora — APPROVED** [review]

**Review by Sfiguz7 — APPROVED** [review]
