### PR TITLE
fix dupe glitch with backpacks

### LINKED ISSUE #4130: Item dupe with backpacks and a big player profile
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

An item dupe bug that can be done by opening backpack that was given by another player who has a huge player file (10.1MB), with hundreds of backpacks (599 to be exact)

### 📑 Reproduction Steps

Step 0: Restart server, ensures that other player's backpacks will be unloaded prior to starting the dupe process
Step 1: Open up a backpack of a person who has made a ton of backpacks with possibly a ton of items in them
Step 2: Server lags, after which the backpack will open
Step 3: Take items out of the backpack somewhat quickly, then close the interface or wait for it to refresh on its own
Step 4: Open the backpack again, which opens instantly without any lag assuming the interface was closed
Step 5: The original items that were taken out are both still in the backpack and your inventory, which means that the items were duped

### 💡 Expected Behavior

I expected items to not get duped

### 📷 Screenshots / Videos

_No response_

### 📜 Server Log

_No response_

### 📂 `/error-reports/` folder

_No response_

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

 This Server uses the following setup of Slimefun:
 Purpur git-Purpur-1985 (MC: 1.19.4)
 Slimefun Dev - 1136
 Metrics-Module #29
 Java 17
 Installed Addons: (8)
   Networks vDEV - 50 (git 3de3c9d6)
   InfinityExpansion vDEV - 144 (git 9da37202)
   SFCalc vDev - 38
   MobCapturer vDEV - 33 (git 6fc26c35)
   HotbarPets vDEV - 38 (git fa6c871d)
   EcoPower vDEV - 5 (git 5c1ecd68)
   FluffyMachines vDEV - 132 (git ccf029ba)
   ExoticGarden vDEV - 78 (git 7f9a5f63)

### 🧭 Other plugins

_No response_

### PR DESCRIPTION
**Pull request by J3fftw1**
## Description
This PR fixes a dupe glitch with backpacks. There was a race condition in PlayerProfile where the UUID got removed from the loading map before it was finished loading and inserted into the Registry. This meant that the PlayerProfile could load twice if someone did something like spam open a backpack after joining.
We now finish loading and adding to the registry before marking it as no longer loading.

## Proposed changes
Move where we finish loading (remove from the loading map) to ensure we're always after the registry.

## Related Issues (if applicable)
Fixes #4130 
possibly fix for #4131 

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I have made sure that the proposed changes do not break compatibility across the supported Minecraft versions (1.16.* - 1.20.*).
- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

File: src/main/java/io/github/thebusybiscuit/slimefun4/api/player/PlayerProfile.java [hunk 1]
```diff
@@ -394,12 +394,18 @@ public static boolean get(@Nonnull OfflinePlayer p, @Nonnull Consumer<PlayerProf
...
             PlayerData data = Slimefun.getPlayerStorage().loadPlayerData(p.getUniqueId());
-            loading.remove(uuid);
 
             AsyncProfileLoadEvent event = new AsyncProfileLoadEvent(new PlayerProfile(p, data));
             Bukkit.getPluginManager().callEvent(event);
 
             Slimefun.getRegistry().getPlayerProfiles().put(uuid, event.getProfile());
+
+            // Make sure we call this after we actually put the PlayerProfile into the map.
+            // Otherwise we end up with a race condition where the profile is not in the map just _yet_
```
Comment (WalshyDev) [inline src/main/java/io/github/thebusybiscuit/slimefun4/api/player/PlayerProfile.java:404]:
```suggestion
            // Otherwise, we end up with a race condition where the profile is not in the map just _yet_
```

File: src/main/java/io/github/thebusybiscuit/slimefun4/api/player/PlayerProfile.java [hunk 2]
```diff
@@ -434,10 +440,15 @@ public static boolean request(@Nonnull OfflinePlayer p) {
             // Should probably prevent multiple requests for the same profile in the future
             Slimefun.getThreadService().newThread(Slimefun.instance(), "PlayerProfile#request(" + uuid + ")", () -> {
                 PlayerData data = Slimefun.getPlayerStorage().loadPlayerData(uuid);
-                loading.remove(uuid);
 
                 PlayerProfile pp = new PlayerProfile(p, data);
                 Slimefun.getRegistry().getPlayerProfiles().put(uuid, pp);
+
+                // Make sure we call this after we actually put the PlayerProfile into the map.
+                // Otherwise we end up with a race condition where the profile is not in the map just _yet_
```
Comment (WalshyDev) [inline src/main/java/io/github/thebusybiscuit/slimefun4/api/player/PlayerProfile.java:448]:
```suggestion
                // Otherwise, we end up with a race condition where the profile is not in the map just _yet_
```

File: src/main/java/io/github/thebusybiscuit/slimefun4/api/player/PlayerProfile.java [hunk 3]
```diff
@@ -394,12 +394,18 @@ public static boolean get(@Nonnull OfflinePlayer p, @Nonnull Consumer<PlayerProf
...
         Slimefun.getThreadService().newThread(Slimefun.instance(), "PlayerProfile#get(" + uuid + ")", () -> {
             PlayerData data = Slimefun.getPlayerStorage().loadPlayerData(p.getUniqueId());
-            loading.remove(uuid);
 
             AsyncProfileLoadEvent event = new AsyncProfileLoadEvent(new PlayerProfile(p, data));
             Bukkit.getPluginManager().callEvent(event);
 
             Slimefun.getRegistry().getPlayerProfiles().put(uuid, event.getProfile());
+
+            // Make sure we call this after we actually put the PlayerProfile into the map.
```
Comment (WalshyDev) [inline src/main/java/io/github/thebusybiscuit/slimefun4/api/player/PlayerProfile.java:403]:
```suggestion
            // Make sure we call this after we put the PlayerProfile into the registry.
```

File: src/main/java/io/github/thebusybiscuit/slimefun4/api/player/PlayerProfile.java [hunk 4]
```diff
@@ -434,10 +440,15 @@ public static boolean request(@Nonnull OfflinePlayer p) {
             // Should probably prevent multiple requests for the same profile in the future
             Slimefun.getThreadService().newThread(Slimefun.instance(), "PlayerProfile#request(" + uuid + ")", () -> {
                 PlayerData data = Slimefun.getPlayerStorage().loadPlayerData(uuid);
-                loading.remove(uuid);
 
                 PlayerProfile pp = new PlayerProfile(p, data);
                 Slimefun.getRegistry().getPlayerProfiles().put(uuid, pp);
+
+                // Make sure we call this after we actually put the PlayerProfile into the map.
```
Comment (WalshyDev) [inline src/main/java/io/github/thebusybiscuit/slimefun4/api/player/PlayerProfile.java:447]:
```suggestion
                // Make sure we call this after we put the PlayerProfile into the registry.
```

**Review by WalshyDev — APPROVED** [review]

**Review by Sfiguz7 — APPROVED** [review]
