### PR TITLE
Ancient Pedestal Fixes

### LINKED ISSUE #2940: Items on Ancient Pedestal can be moved with water.
## :round_pushpin: Description (REQUIRED)

Items on Ancient Pedestal can be moved with water. After you moved the item so that it doesn't on the top of the pedestal it can't be picked up, unless you move back the item to the top of the Ancient Pedestal.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Place Ancient Pedestal
2. Put an item on it
3. Place a water to move the items
4. See the items moving and be unable to be picked up
Additional steps to 'retrieve the item back':
5. Move back the item so it just barely on the top on the Pedestal
6. Right click the pedestal to pickup the item back.

https://user-images.githubusercontent.com/34732414/113651849-f8602280-96bc-11eb-8044-27ea2810d6d9.mp4

## :bulb: Expected behavior (REQUIRED)

Items on Ancient Pedestal should not be able to be moved with water.

## :scroll: Server Log

There is no relevant logs.

## :open_file_folder: /error-reports/ Folder

There is no error logs.

## :compass: Environment (REQUIRED)

image

### LINKED ISSUE #3147: Items on Ancient Pedestal can be moved with falling block
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [x] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Gravity blocks like snad can not be place upon the Ancient Pedestal. But if it was placed one block higher, the item will be moved and can't be picked up.

### 📑 Reproduction Steps

1. Place Ancient Pedestal
2. Put an item on it
3. Place a gravity block one block upon it

### 💡 Expected Behavior

The item can't be moved or a gravity block can't be placed upon Ancient Pedestal

### 📷 Screenshots / Videos

https://user-images.githubusercontent.com/69747100/124416498-b57c1c80-dd89-11eb-885b-3130618c7ecb.mp4

QQ截图20210705120950

### 📜 Server Log

_No response_

### 📂 `/error-reports/` folder

_No response_

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.16.x

### ⭐ Slimefun version

Slimefun4 - DEV 943 (git 51bfb)

### 🧭 Other plugins

_No response_

### LINKED ISSUE #3444: Could not pass event PlayerRightClickEvent to Slimefun
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

```
com.destroystokyo.paper.exception.ServerEventException: Could not pass event PlayerRightClickEvent to Slimefun vDEV - 999 (git e02eedd9)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:647)
	at Slimefun4.jar//io.github.thebusybiscuit.slimefun4.implementation.listeners.SlimefunItemInteractListener.onRightClick(SlimefunItemInteractListener.java:62)
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor375.execute(Unknown Source)
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
	at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:543)
	at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:542)
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1815)
	at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:33)
	at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:9)
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
	at net.minecraft.server.TickTask.run(TickTask.java:18)
	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1426)
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192)
	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1404)
	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1397)
	at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
	at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1375)
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1286)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "customName" is null
	at Slimefun4.jar//io.github.thebusybiscuit.slimefun4.implementation.items.altar.AncientPedestal.getOriginalItemStack(AncientPedestal.java:112)
	at Slimefun4.jar//io.github.thebusybiscuit.slimefun4.implementation.listeners.AncientAltarListener.usePedestal(AncientAltarListener.java:159)
	at Slimefun4.jar//io.github.thebusybiscuit.slimefun4.implementation.listeners.AncientAltarListener.onInteract(AncientAltarListener.java:111)
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor440.execute(Unknown Source)
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
	at Slimefun4.jar//io.github.thebusybiscuit.slimefun4.implementation.listeners.SlimefunItemInteractListener.onRightClick(SlimefunItemInteractListener.java:62)
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor375.execute(Unknown Source)
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
	at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:543)
	at app//net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:542)
	at app//net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1815)
	at app//net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:33)
	at app//net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9)
	at app//net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56)
	at app//net.minecraft.server.TickTask.run(TickTask.java:18)
	at app//net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149)
	at app//net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23)
	at app//net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426)
	at app//net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192)
	at app//net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122)
	at app//net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404)
	at app//net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397)
	at app//net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132)
	at app//net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1375)
	at app//net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1286)
	... 2 more
```

### 📑 Reproduction Steps

Not sure.

### 💡 Expected Behavior

N/A

### 📷 Screenshots / Videos

_No response_

### 📜 Server Log

_No response_

### 📂 `/error-reports/` folder

_No response_

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.17.x

### ⭐ Slimefun version

```
> sf versions
[03:04:41 INFO]: This Server uses the following setup of Slimefun:
Paper git-Paper-408 (MC: 1.17.1)
Slimefun DEV - 999 (git e02eedd9)
Metrics-Module #28
Java 17

Installed Addons: (3)
  EcoPower vDEV - 5 (git 5c1ecd68)
  SlimefunLuckyBlocks vDEV - 36 (git 60f0c8dc)
  ExoticGarden vDEV - 77 (git a2c4b6d3)
```

### 🧭 Other plugins

_No response_

### LINKED ISSUE #3507: Ancient Altar will rename potion items
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Ancient Altar will rename the potion, splash potion, lingering potion and potion arrow name.

### 📑 Reproduction Steps

1. Place potion type item to Ancient Altar
2. Take it down
3. See it will show include `[]` item name

### 💡 Expected Behavior

Don't rename the any potion type items, and take back will show normal vanilla item name.

### 📷 Screenshots / Videos

Before put on the Ancient Altar
image
image
image
image

After take down from the Ancient Altar
image
image
image
image

### 📜 Server Log

_No response_

### 📂 `/error-reports/` folder

_No response_

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.18.x

### ⭐ Slimefun version

image

### 🧭 Other plugins

_No response_

### PR DESCRIPTION
**Pull request by JustAHuman-xD**
## Description
To fix the various problems people can encounter with the ancient pedestal, this is my re-write of #3637 

## Proposed changes
- Added ArmorStandUtils.java
- Added ArmorStandUtils#createArmorStand
- HologramProjector now uses ArmorStandUtils#createArmorStand
- Ancient Pedestal now implements NotHopperable
- Ancient Pedestal now uses ArmorStandUtils#createArmorStand to create an invisible armorstand, and sets the item as its passenger to prevent it from being moved by things like fluids and falling blocks
- Marked the item for an ancient pedestal be Invulnerable & UnlimitedLifeTime (To fix items despawning and making players loose their items)

## Related Issues (if applicable)
Resolves #2940 
Resolves #3147
Resolves #3444
Resolves #3507 

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I have made sure that the proposed changes do not break compatibility across the supported Minecraft versions (1.16.* - 1.19.*).
- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

File: src/main/java/io/github/thebusybiscuit/slimefun4/utils/ArmorStandUtils.java [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+ */
+public class ArmorStandUtils {
+    /**
+     * Spawns an {@link ArmorStand} at the given {@link Location}
+     * (Invisible, Silent, Marker, NoGravity, NoBasePlate, NoRemoveWhenFarAway)
+     *
+     * @param location The {@link Location} to spawn the {@link ArmorStand}
+     * @return The spawned {@link ArmorStand}
+     */
+    public static ArmorStand spawnArmorStand(@Nonnull Location location) {
```
Comment (Sefiraat) [inline src/main/java/io/github/thebusybiscuit/slimefun4/utils/ArmorStandUtils.java:28]: Can you annotate this `@Nonnull` please (or check nullability when it's used, but I think nonnull would be preferable here)

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/blocks/HologramProjector.java [hunk 2]
```diff
@@ -153,23 +153,12 @@ private static ArmorStand getArmorStand(@Nonnull Block projector, boolean create
             return null;
         }
 
-        ArmorStand hologram = spawnArmorStand(l);
+        ArmorStand hologram = ArmorStandUtils.spawnArmorStand(l);
+        hologram.setCustomNameVisible(true);
```
Comment (Sefiraat) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/blocks/HologramProjector.java:157]: Given you have now moved this to a util method, could we perhaps add overloads to that method to return a armorstand with a display name/visible name? Optional, however

**Review by Sefiraat — DISMISSED** [review]
Feel like we can/should expand the util a little bit that's out of scope for the PR and what you have here looks good to me!

**Comment by JustAHuman-xD** [comment]
Going to make a commit to fix the import order but other than that any chance this could be reviewed?

**Comment by JustAHuman-xD** [comment]
_Any chance this could get reviewed soon?_

**Review by svr333 — DISMISSED** [review]
looks good to me, didnt see anything

File: src/main/java/io/github/thebusybiscuit/slimefun4/utils/ArmorStandUtils.java [hunk 3]
```diff
@@ -0,0 +1,56 @@
...
+ * This class holds utilities for {@link ArmorStand}, useful for classes
+ * dealing with {@link ArmorStand}s that are not from {@link HologramsService}
+ *
+ * @see HologramProjector
+ * @see AncientPedestal
+ *
+ * @author JustAHuman
+ */
+public class ArmorStandUtils {
+    /**
```
Comment (WalshyDev) [inline src/main/java/io/github/thebusybiscuit/slimefun4/utils/ArmorStandUtils.java:22]:
```suggestion

    /**
```

File: src/main/java/io/github/thebusybiscuit/slimefun4/utils/ArmorStandUtils.java [hunk 4]
```diff
@@ -0,0 +1,56 @@
...
+     * Spawns an {@link ArmorStand} at the given {@link Location} with the given custom name
+     * (Invisible, Silent, Marker, NoGravity, NoBasePlate, NoRemoveWhenFarAway, VisibleCustomName)
```
Comment (WalshyDev) [inline src/main/java/io/github/thebusybiscuit/slimefun4/utils/ArmorStandUtils.java:24]: ? what is this list for?

File: src/main/java/io/github/thebusybiscuit/slimefun4/utils/ArmorStandUtils.java [hunk 5]
```diff
@@ -0,0 +1,56 @@
...
+    public static @Nonnull ArmorStand spawnArmorStand(@Nonnull Location location, @Nonnull String customName) {
+        ArmorStand armorStand = spawnArmorStand(location);
+        armorStand.setCustomName(customName);
+        armorStand.setCustomNameVisible(true);
+        return armorStand;
+    }
+    
+    /**
+     * Spawns an {@link ArmorStand} at the given {@link Location}
+     * (Invisible, Silent, Marker, NoGravity, NoBasePlate, NoRemoveWhenFarAway)
```
Comment (WalshyDev) [inline src/main/java/io/github/thebusybiscuit/slimefun4/utils/ArmorStandUtils.java:40]: same here

**Review by WalshyDev — COMMENTED** [review]
Looks good, just a few small things

File: src/main/java/io/github/thebusybiscuit/slimefun4/utils/ArmorStandUtils.java (hunk 4 above)
Comment (JustAHuman-xD) [reply src/main/java/io/github/thebusybiscuit/slimefun4/utils/ArmorStandUtils.java:25]: Just to tell who ever is using the util the settings the armorstand has

File: src/main/java/io/github/thebusybiscuit/slimefun4/utils/ArmorStandUtils.java (hunk 5 above)
Comment (JustAHuman-xD) [reply src/main/java/io/github/thebusybiscuit/slimefun4/utils/ArmorStandUtils.java:41]: > Just to tell who ever is using the util the settings the armorstand has

File: src/main/java/io/github/thebusybiscuit/slimefun4/utils/ArmorStandUtils.java (hunk 4 above)
Comment (WalshyDev) [reply src/main/java/io/github/thebusybiscuit/slimefun4/utils/ArmorStandUtils.java:25]: If we want to list these I'd make it a proper message. `Set properties: <list>`
This will also just be part of the first line, I think you're wanting a line break here (`<br />`)

**Review by WalshyDev — DISMISSED** [review]

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/altar/AncientPedestal.java [hunk 6]
```diff
@@ -103,17 +129,24 @@ private boolean testItem(@Nullable Entity n) {
             return false;
         }
     }
+    
+    private boolean testArmorStand(@Nullable Entity n) {
+        if (n instanceof ArmorStand armorStand && armorStand.isValid()) {
+            String customName = armorStand.getCustomName();
```
Comment (J3fftw1) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/altar/AncientPedestal.java:135]: variable isnt needed here.

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/altar/AncientPedestal.java [hunk 7]
```diff
@@ -123,7 +156,8 @@ private boolean testItem(@Nullable Entity n) {
 
     public void placeItem(@Nonnull Player p, @Nonnull Block b) {
         ItemStack hand = p.getInventory().getItemInMainHand();
-        ItemStack displayItem = new CustomItemStack(hand, ITEM_PREFIX + System.nanoTime());
+        String displayName = ITEM_PREFIX + System.nanoTime();
+        ItemStack displayItem = new CustomItemStack(hand, displayName);
```
Comment (J3fftw1) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/altar/AncientPedestal.java:160]: Any reason this is split up?

**Review by J3fftw1 — CHANGES_REQUESTED** [review]

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/altar/AncientPedestal.java (hunk 7 above)
Comment (JustAHuman-xD) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/altar/AncientPedestal.java:160]: Yeah if you scroll down it's used with the armorstand as well

**Comment by variananora** [comment]
> Did you happen to test that the hologram projector still worked as intended? As it's code was changed.

Ah I didn't see that, will update the test later this noon

**Comment by JustAHuman-xD** [comment]
Just tested old ancient pedestals having items on and stopping the server, switching to test build and was able to properly pick them and generate the armorstands upon using it again, unless anyone has anything else to test it should be good 👍

**Review by J3fftw1 — APPROVED** [review]
LGTM

**Review by Sfiguz7 — APPROVED** [review]
LGTM
