### PR TITLE
Fix industrial miner mining up sf blocks

### LINKED ISSUE #3511: Industrial Miner mines mob simulation chamber from infinity expansion.
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Linking the discord discussion here. I was able to confirm this is a bug.
https://discord.com/channels/565557184348422174/565569196218384385/958476080820420659

when a mob simulation chamber is within the range of the industrial miner, it mines it as gilded blackstone. the slimefun block data is still there. when you place any block back where the mob sim chamber was, it drops the chamber. 

### 📑 Reproduction Steps

1. Setup the industrial miner
2. place a mob simulation chamber below the miner within its mining range
3. start up the miner
4. it will collect it as gilded blackstone and leave the slimefun data.

### 💡 Expected Behavior

I would expect it to not mine the mob simulation chamber.

### 📷 Screenshots / Videos

_No response_

### 📜 Server Log

no errors in log

### 📂 `/error-reports/` folder

_No response_

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.18.x

### ⭐ Slimefun version

1008

### 🧭 Other plugins

_No response_

### PR DESCRIPTION
**Pull request by FN-FAL113**
## Description
Prevent the industrial miner from mining any sf blocks that uses ores as their material

## Proposed changes
- Blockstorage checks

## Related Issues (if applicable)
- Resolves #3511 

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/miner/MiningTask.java [hunk 1]
```diff
@@ -143,6 +143,7 @@ private void warmUp() {
             if (fuelLevel <= 0) {
                 // This Miner has not enough fuel.
```
Comment (Sefiraat) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/miner/MiningTask.java:144]:
```suggestion
                // This Miner has not got enough fuel to run.
```

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/miner/IndustrialMiner.java [hunk 2]
```diff
@@ -202,22 +203,22 @@ public void onInteract(Player p, Block b) {
...
-            return canMineAncientDebris.getValue();
-        } else if (version.isAtLeast(MinecraftVersion.MINECRAFT_1_17) && SlimefunTag.DEEPSLATE_ORES.isTagged(type)) {
-            return canMineDeepslateOres.getValue();
+        if (version.isAtLeast(MinecraftVersion.MINECRAFT_1_16) && block.getType() == Material.ANCIENT_DEBRIS) {
+            return canMineAncientDebris.getValue() && !BlockStorage.hasBlockInfo(block);
+        } else if (version.isAtLeast(MinecraftVersion.MINECRAFT_1_17) && SlimefunTag.DEEPSLATE_ORES.isTagged(block.getType())) {
+            return canMineDeepslateOres.getValue() && !BlockStorage.hasBlockInfo(block);
         } else {
-            return SlimefunTag.INDUSTRIAL_MINER_ORES.isTagged(type);
+            return SlimefunTag.INDUSTRIAL_MINER_ORES.isTagged(block.getType()) && !BlockStorage.hasBlockInfo(block);
```
Comment (Sefiraat) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/miner/IndustrialMiner.java:221]: A minor thing but can we add `Material type = block.getType()` above this just to make the if statements a tiny bit more readable.

**Review by Sefiraat — CHANGES_REQUESTED** [review]

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/miner/IndustrialMiner.java [hunk 3]
```diff
@@ -212,8 +212,9 @@ public void onInteract(Player p, Block b) {
      */
     public boolean canMine(@Nonnull Block block) {
         MinecraftVersion version = Slimefun.getMinecraftVersion();
+        Material type = block.getType();
 
-        if (version.isAtLeast(MinecraftVersion.MINECRAFT_1_16) && block.getType() == Material.ANCIENT_DEBRIS) {
+        if (version.isAtLeast(MinecraftVersion.MINECRAFT_1_16) && type == Material.ANCIENT_DEBRIS) {
             return canMineAncientDebris.getValue() && !BlockStorage.hasBlockInfo(block);
         } else if (version.isAtLeast(MinecraftVersion.MINECRAFT_1_17) && SlimefunTag.DEEPSLATE_ORES.isTagged(block.getType())) {
```
Comment (Sefiraat) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/miner/IndustrialMiner.java:219]: It can be used here also

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/miner/IndustrialMiner.java [hunk 4]
```diff
@@ -202,22 +203,23 @@ public void onInteract(Player p, Block b) {
...
         if (version.isAtLeast(MinecraftVersion.MINECRAFT_1_16) && type == Material.ANCIENT_DEBRIS) {
-            return canMineAncientDebris.getValue();
-        } else if (version.isAtLeast(MinecraftVersion.MINECRAFT_1_17) && SlimefunTag.DEEPSLATE_ORES.isTagged(type)) {
-            return canMineDeepslateOres.getValue();
+            return canMineAncientDebris.getValue() && !BlockStorage.hasBlockInfo(block);
+        } else if (version.isAtLeast(MinecraftVersion.MINECRAFT_1_17) && SlimefunTag.DEEPSLATE_ORES.isTagged(block.getType())) {
+            return canMineDeepslateOres.getValue() && !BlockStorage.hasBlockInfo(block);
         } else {
-            return SlimefunTag.INDUSTRIAL_MINER_ORES.isTagged(type);
+            return SlimefunTag.INDUSTRIAL_MINER_ORES.isTagged(block.getType()) && !BlockStorage.hasBlockInfo(block);
```
Comment (Sefiraat) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/miner/IndustrialMiner.java:222]: And here

**Review by Sefiraat — APPROVED** [review]
Looking ok to me 👍

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/miner/IndustrialMiner.java [hunk 5]
```diff
@@ -202,22 +203,23 @@ public void onInteract(Player p, Block b) {
...
+     * @return Whether this {@link IndustrialMiner} is capable of mining this {@link Block}
      */
-    public boolean canMine(@Nonnull Material type) {
+    public boolean canMine(@Nonnull Block block) {
         MinecraftVersion version = Slimefun.getMinecraftVersion();
+        Material type = block.getType();
 
-        if (type == Material.ANCIENT_DEBRIS) {
-            return canMineAncientDebris.getValue();
+        if (version.isAtLeast(MinecraftVersion.MINECRAFT_1_16) && type == Material.ANCIENT_DEBRIS) {
```
Comment (Sefiraat) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/miner/IndustrialMiner.java:217]: Ah, hold up, we dont need a version check here for 1.16 anymore

**Review by Sefiraat — CHANGES_REQUESTED** [review]

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/miner/IndustrialMiner.java (hunk 5 above)
Comment (FN-FAL113) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/miner/IndustrialMiner.java:217]: alrighty, I'm already on outdated on this pull request for many months now, kinda rusty on mc development

**Comment by FN-FAL113** [comment]
lol I just pulled latest stuffs on my main branch, jeez no worries though there is only 1 pull request left from me

**Review by Sefiraat — APPROVED** [review]
👍

**Comment by FN-FAL113** [comment]
> lol I just pulled latest stuffs on my main branch, jeez no worries though there is only 1 pull request left from me

actually nevermind, its all good, main branch was left untouched on my fork

**Review by svr333 — APPROVED** [review]

**Review by JustAHuman-xD — APPROVED** [review]
LGTM

**Review by Sfiguz7 — APPROVED** [review]
LGTM
