### PR TITLE
Attempt to fix bug #2360

### LINKED ISSUE #2360: The refinery can be used as normal piston
## :round_pushpin: Description (REQUIRED)

The refinery can be used as normal piston.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Give a refinery and place.
2. Place a lever next to the refinery.
3. Use lever.

## :bulb: Expected behavior (REQUIRED)

The refinery can not used as normal piston.

## :open_file_folder: /error-reports/ Folder

No error report.

## :compass: Environment (REQUIRED)

 - Server Software (Spigot/Paper): Paper
 - Minecraft Version: 1.16.3
 - Slimefun Version: vDEV - 685 (git dc551907)
 - CS-CoreLib Version: vDEV - 91 (git e42a05d1)

### PR DESCRIPTION
**Pull request by Chlorophytus**
## Description
Attempt to fix a bug where refineries can be used as pistons
## Changes
Checks if the following condition has been met (Check if the event fired on a piston that has Slimefun block data)
```java
BlockStorage.check(e.getBlock()) != null
```

## Related Issues
Resolves #2360 

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockPhysicsListener.java [hunk 1]
```diff
@@ -54,17 +55,23 @@ public void onBlockFall(EntityChangeBlockEvent e) {
 
     @EventHandler
     public void onPistonExtend(BlockPistonExtendEvent e) {
-        for (Block b : e.getBlocks()) {
-            if (BlockStorage.hasBlockInfo(b) || (b.getRelative(e.getDirection()).getType() == Material.AIR && BlockStorage.hasBlockInfo(b.getRelative(e.getDirection())))) {
-                e.setCancelled(true);
-                return;
+        if(BlockStorage.check(e.getBlock()) != null) {
```
Comment (poma123) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockPhysicsListener.java:58]: Please use BlockStorage#hasBlockInfo() instead. Also, formatting (put a space after `if`)

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockPhysicsListener.java [hunk 2]
```diff
@@ -54,17 +55,23 @@ public void onBlockFall(EntityChangeBlockEvent e) {
...
+                    return;
+                }
             }
         }
     }
 
     @EventHandler
     public void onPistonRetract(BlockPistonRetractEvent e) {
-        if (e.isSticky()) {
+        if(BlockStorage.check(e.getBlock()) != null) {
```
Comment (poma123) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockPhysicsListener.java:72]: Please use BlockStorage#hasBlockInfo() instead. Also, formatting (put a space after `if`)

**Review by poma123 — CHANGES_REQUESTED** [review]

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockPhysicsListener.java [hunk 3]
```diff
@@ -54,17 +55,23 @@ public void onBlockFall(EntityChangeBlockEvent e) {
 
     @EventHandler
     public void onPistonExtend(BlockPistonExtendEvent e) {
-        for (Block b : e.getBlocks()) {
-            if (BlockStorage.hasBlockInfo(b) || (b.getRelative(e.getDirection()).getType() == Material.AIR && BlockStorage.hasBlockInfo(b.getRelative(e.getDirection())))) {
-                e.setCancelled(true);
-                return;
+        if(BlockStorage.check(e.getBlock()) != null) {
+            e.setCancelled(true);
+        } else {
```
Comment (poma123) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockPhysicsListener.java:60]: Please put `else {` to a new line.

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockPhysicsListener.java [hunk 4]
```diff
@@ -54,17 +55,23 @@ public void onBlockFall(EntityChangeBlockEvent e) {
...
+            for (Block b : e.getBlocks()) {
+                if (BlockStorage.hasBlockInfo(b) || (b.getRelative(e.getDirection()).getType() == Material.AIR && BlockStorage.hasBlockInfo(b.getRelative(e.getDirection())))) {
+                    e.setCancelled(true);
+                    return;
```
Comment (LinoxGH) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockPhysicsListener.java:64]: This is redundant.

**Review by poma123 — CHANGES_REQUESTED** [review]

**Review by LinoxGH — CHANGES_REQUESTED** [review]

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockPhysicsListener.java [hunk 5]
```diff
@@ -54,17 +55,23 @@ public void onBlockFall(EntityChangeBlockEvent e) {
...
             }
         }
     }
 
     @EventHandler
     public void onPistonRetract(BlockPistonRetractEvent e) {
-        if (e.isSticky()) {
+        if(BlockStorage.check(e.getBlock()) != null) {
+            e.setCancelled(true);
+        } else if (e.isSticky()) {
```
Comment (poma123) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockPhysicsListener.java:74]: Put `else if` to a new line please

**Review by poma123 — CHANGES_REQUESTED** [review]

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockPhysicsListener.java (hunk 5 above)
Comment (Chlorophytus) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockPhysicsListener.java]: Change has been performed.

Comment (poma123) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockPhysicsListener.java]: Thank you! You can mark them as resolved by pushing the "Resolve conversation" button!

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockPhysicsListener.java (hunk 4 above)
Comment (poma123) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockPhysicsListener.java:65]: Only `return;` is redundant here.
```suggestion
```

Comment (poma123) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockPhysicsListener.java:65]: There could be a `break;` instead.

**Review by poma123 — COMMENTED** [review]
Pretty much approving this. I'm going to test it out ingame.

**Review by poma123 — APPROVED** [review]
Looking good. Thanks for your contribution!

**Review by LinoxGH — APPROVED** [review]
