### PR TITLE
Make Fire Staff not disenchantable by default

### LINKED ISSUE #3768: Elemental Staff - Fire should not be usable in disenchanters
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

this is a bug regarding Elemental Staff - Fire  

### 📑 Reproduction Steps

if the bug start when player put stacks

### 💡 Expected Behavior

i have suggestion add only 1 stick per time

### 📷 Screenshots / Videos

https://www.youtube.com/watch?v=A6NEFDFA2Qw

### 📜 Server Log

_No response_

### 📂 `/error-reports/` folder

_No response_

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

Dev - 1043

### 🧭 Other plugins

_No response_

### PR DESCRIPTION
**Pull request by Phoenix-Starlight**
## Description

To make the Elemental Staff - Fire not disenchantable by default.
## Proposed changes

Creation of a Slimefun item class and altering the item setup to use this class.
This won't work with existing `Items.yml` so existing servers need to edit the file to reflect this change.
## Related Issues (if applicable)

Resolves #3768 
## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I have made sure that the proposed changes do not break compatibility across the supported Minecraft versions (1.16.* - 1.19.*).
- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/staves/FireStaff.java [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+ */
+public class FireStaff extends SlimefunItem {
+
+    @ParametersAreNonnullByDefault
+    public FireStaff(ItemGroup itemGroup, SlimefunItemStack item, RecipeType recipeType, ItemStack[] recipe) {
+        super(itemGroup, item, recipeType, recipe);
+        disenchantable = false;
+    }
+
+}
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/staves/FireStaff.java:29]: Could probably be generalized into `EnchantedStaff` or `EnchantedStick`

**Review by TheBusyBiscuit — CHANGES_REQUESTED** [review]

**Review by TheBusyBiscuit — COMMENTED** [review]
Sorry for making you change the name again.
What do you think about `PermanentlyEnchantedItem`?

I think that might be more indicative of the fact that it isn't just enchanted but cannot be disenchanted.

**Review by TheBusyBiscuit — APPROVED** [review]
LGTM

**Review by svr333 — APPROVED** [review]

**Comment by Sfiguz7** [comment]
Should we maybe add other items to this? Like the infused elytra

**Comment by Phoenix-Starlight** [comment]
Perhaps, in my view as long as enchantments do not exceed vanilla limits
they can be disenchanted, however I understand the view where it should be
by default not dis-enchantable. (Too easy method to get enchantments etc.)

**Comment by Sfiguz7** [comment]
Eh I guess for the other stuff servers can still decide to change the `is_enchantable` flag in items.yml, the situation is clearly different for the fire staff since it keeps its "effects" even after being disenchanted (contrarily to armor tools and weapons).
I think this works just fine then!
