### PR TITLE
Fix possible custom enchantment duplication

### LINKED ISSUE #3837: Eco Enchants and Auto Disenchanter Enchantment Dupe
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When removing a custom enchant (ecoenchants) using auto-disenchanter the enchant will remove and give you the book and the enchant will also stay on the item.

### 📑 Reproduction Steps

1. Disenchant a custom enchant from a item using the disenchanter table
2. Get the book it gives and remove item
3. Enchant stays on item and gives you a book

### 💡 Expected Behavior

Disenchant a custom enchant from a item using the disenchanter table
Get the book it gives and remove item
Enchant removes from item and gives you a book with enchant on

### 📷 Screenshots / Videos

_No response_

### 📜 Server Log

_No response_

### 📂 `/error-reports/` folder

_No response_

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

Slimefun Dev 1050

### 🧭 Other plugins

EcoEnchants

### PR DESCRIPTION
**Pull request by justtos**
## Description

This PR fixes a possible duplication of custom enchantments due to inconsistencies in the `removeEnchantment` method of class `ItemStack` between Spigot and Paper due to [Paper Server Patch 0069](https://github.com/PaperMC/Paper/blob/b1696788d61ddc338bd2e61fac3b43ff60c432e1/patches/server/0069-Handle-Item-Meta-Inconsistencies.patch#L111C25-L111C25).

_Has been tested on Spigot and Paper 1.19.2 only._
## Proposed changes

Changed to method `removeEnchant` of class `ItemMeta` from the method `removeEnchantment` of class `ItemStack`, by also moving the `item.setItemMeta(itemMeta)` after the for loop.

Added a check and logger in hopes to prevent future enchantment duplication.
## Related Issues (if applicable)

Resolves #3837
## Checklist

- [X] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I have made sure that the proposed changes do not break compatibility across the supported Minecraft versions (1.16.* - 1.20.*).
- [x] I followed the existing code standards and didn't mess up the formatting.
- [X] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoDisenchanter.java [hunk 1]
```diff
@@ -128,16 +130,22 @@ private void transferEnchantments(ItemStack item, ItemStack book, Map<Enchantmen
...
         EnchantmentStorageMeta meta = (EnchantmentStorageMeta) book.getItemMeta();
 
         for (Map.Entry<Enchantment, Integer> entry : enchantments.entrySet()) {
-            item.removeEnchantment(entry.getKey());
-            meta.addStoredEnchant(entry.getKey(), entry.getValue(), true);
+            boolean wasEnchantmentRemoved = itemMeta.removeEnchant(entry.getKey()),
+                    stillHasEnchantment = itemMeta.getEnchants().containsKey(entry.getKey());
+
+            // Prevent future enchantment duplication
+            if(wasEnchantmentRemoved && !stillHasEnchantment)
```
Comment (svr333) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoDisenchanter.java:142]: minor code styling
```suggestion
            boolean wasEnchantmentRemoved = itemMeta.removeEnchant(entry.getKey());
            boolean stillHasEnchantment = itemMeta.getEnchants().containsKey(entry.getKey());

            // Prevent future enchantment duplication
            if (wasEnchantmentRemoved && !stillHasEnchantment)
```

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoDisenchanter.java [hunk 2]
```diff
@@ -128,16 +130,22 @@ private void transferEnchantments(ItemStack item, ItemStack book, Map<Enchantmen
...
-            item.removeEnchantment(entry.getKey());
-            meta.addStoredEnchant(entry.getKey(), entry.getValue(), true);
+            boolean wasEnchantmentRemoved = itemMeta.removeEnchant(entry.getKey());
+            boolean stillHasEnchantment = itemMeta.getEnchants().containsKey(entry.getKey());
+
+            // Prevent future enchantment duplication
+            if (wasEnchantmentRemoved && !stillHasEnchantment)
+                meta.addStoredEnchant(entry.getKey(), entry.getValue(), true);
+            else //                                                                                                     Get Enchantment "Name"
+                Slimefun.logger().log(Level.SEVERE, "AutoDisenchanter has failed to remove enchantment \"{0}\"", entry.getKey().getKey().getKey());
```
Comment (JustAHuman-xD) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoDisenchanter.java:145]: You're missing some Brackets [(Code Style Guidelines)](https://github.com/Slimefun/Slimefun4/blob/master/CONTRIBUTING.md#black_nib-code-style-guidelines)

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoDisenchanter.java [hunk 3]
```diff
@@ -139,10 +139,13 @@ private void transferEnchantments(ItemStack item, ItemStack book, Map<Enchantmen
             boolean stillHasEnchantment = itemMeta.getEnchants().containsKey(entry.getKey());
 
             // Prevent future enchantment duplication
-            if (wasEnchantmentRemoved && !stillHasEnchantment)
+            if (wasEnchantmentRemoved && !stillHasEnchantment) {
                 meta.addStoredEnchant(entry.getKey(), entry.getValue(), true);
-            else //                                                                                                     Get Enchantment "Name"
+            }
+            else {
```
Comment (JustAHuman-xD) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoDisenchanter.java:145]:
```suggestion
            } else {
```

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoDisenchanter.java [hunk 4]
```diff
@@ -141,8 +141,7 @@ private void transferEnchantments(ItemStack item, ItemStack book, Map<Enchantmen
             // Prevent future enchantment duplication
             if (wasEnchantmentRemoved && !stillHasEnchantment) {
                 meta.addStoredEnchant(entry.getKey(), entry.getValue(), true);
-            }
-            else {
+            } else {
                 //                                                                                                      Get Enchantment Name
```
Comment (Phoenix-Starlight) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoDisenchanter.java:145]:
```suggestion
                // Get Enchantment Name
```
I don't think these spaces were intended...

Comment (justtos) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoDisenchanter.java:145]: Yep, my bad.

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoDisenchanter.java [hunk 5]
```diff
@@ -2,10 +2,12 @@
 
 import java.util.HashMap;
 import java.util.Map;
+import java.util.logging.Level;
 
 import javax.annotation.Nullable;
 import javax.annotation.ParametersAreNonnullByDefault;
 
+import io.github.thebusybiscuit.slimefun4.implementation.Slimefun;
```
Comment (J3fftw1) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoDisenchanter.java:10]: move the import with the other imports

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoDisenchanter.java [hunk 6]
```diff
@@ -128,16 +130,24 @@ private void transferEnchantments(ItemStack item, ItemStack book, Map<Enchantmen
...
 
         EnchantmentStorageMeta meta = (EnchantmentStorageMeta) book.getItemMeta();
 
         for (Map.Entry<Enchantment, Integer> entry : enchantments.entrySet()) {
-            item.removeEnchantment(entry.getKey());
-            meta.addStoredEnchant(entry.getKey(), entry.getValue(), true);
+            boolean wasEnchantmentRemoved = itemMeta.removeEnchant(entry.getKey());
+            boolean stillHasEnchantment = itemMeta.getEnchants().containsKey(entry.getKey());
+
+            // Prevent future enchantment duplication
```
Comment (J3fftw1) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoDisenchanter.java:141]: mind linking the issue here?

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoDisenchanter.java [hunk 7]
```diff
@@ -128,16 +130,24 @@ private void transferEnchantments(ItemStack item, ItemStack book, Map<Enchantmen
...
+            if (wasEnchantmentRemoved && !stillHasEnchantment) {
+                meta.addStoredEnchant(entry.getKey(), entry.getValue(), true);
+            } else {
+                // Get Enchantment Name
+                Slimefun.logger().log(Level.SEVERE, "AutoDisenchanter has failed to remove enchantment \"{0}\"", entry.getKey().getKey().getKey());
```
Comment (J3fftw1) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoDisenchanter.java:146]: should we log the location as well for if its gonna spam this in console the admins can look into it?

**Review by J3fftw1 — CHANGES_REQUESTED** [review]

**Review by Sfiguz7 — COMMENTED** [review]
Agreed with Jeff's comments, other than that everything looks fine.
I am not marking this as approved yet as once you push your changes we will get a new temporary build automatically and can test in 1.20 too, since you mentioned you only tested in 1.19.2

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoDisenchanter.java (hunk 7 above)
Comment (justtos) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoDisenchanter.java:146]: I don't think it's needed as if it happens it's most likely going to happen for everyone.

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoDisenchanter.java [hunk 8]
```diff
@@ -128,16 +130,24 @@ private void transferEnchantments(ItemStack item, ItemStack book, Map<Enchantmen
...
         ((Repairable) itemMeta).setRepairCost(0);
-        item.setItemMeta(itemMeta);
         book.setItemMeta(bookMeta);
 
         EnchantmentStorageMeta meta = (EnchantmentStorageMeta) book.getItemMeta();
 
         for (Map.Entry<Enchantment, Integer> entry : enchantments.entrySet()) {
-            item.removeEnchantment(entry.getKey());
-            meta.addStoredEnchant(entry.getKey(), entry.getValue(), true);
+            boolean wasEnchantmentRemoved = itemMeta.removeEnchant(entry.getKey());
```
[the remark this answers is not in the document]
Comment (justtos) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoDisenchanter.java:138]: Now it's `enchantmentToTransfer.getKey().getKey()` :)

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoDisenchanter.java (hunk 6 above)
Comment (justtos) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoDisenchanter.java:141]: Added in the following ` (#3837)`

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoDisenchanter.java (hunk 7 above)
Comment (J3fftw1) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/enchanting/AutoDisenchanter.java]: I do think we should log the location.
Because something is likely to happen doesnt mean it will always happen.
not sure exactly how we can get the location tho.
so maybe scrap that idea or if others know  please comment

**Comment by justtos** [comment]
Using the preview build I have tested with both Spigot and Paper 1.20.1 and can confirm works normally.

**Review by J3fftw1 — APPROVED** [review]

**Review by Sfiguz7 — APPROVED** [review]
