### PR TITLE
Fixed 2650

### LINKED ISSUE #2650: Soulbound items do not adhere to the world settings (disabling Slimefun in a world)
## :round_pushpin: Description (REQUIRED)

Soulbound items do not drop out if when die in a world where disabled.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Get a soulbound item, like a chestplate and equip it.
2. Die in a world where disabled the soulbound items.
3. You will respawn with the soulbound item, despite the fact that it is disabled.

## :bulb: Expected behavior (REQUIRED)

Soulbound items drop out if when die in a world where disabled.

## :compass: Environment (REQUIRED)

[16:25:51 INFO]: This Server uses the following setup of Slimefun:
[16:25:51 INFO]: Yatopia v1_16_R3
[16:25:51 INFO]: CS-CoreLib vDEV - 92 (git e9150d72)
[16:25:51 INFO]: Slimefun vDEV - 769 (git d048f7f8)
[16:25:51 INFO]: Metrics build: #6

### PR DESCRIPTION
**Pull request by WalshyDev**
## Description
I thought this was a pretty good and simple fix, I have made another method in SlimefunUtils for isSoulbound which accepts a world. If the item is a SF Item and it has been disabled in that world then soulbound returns false. The same as if it was disabled in general.

Added a unit test to cover this case as well.

## Changes
* SlimefunUtils.isSoulbound(ItemStack, World)
* SlimefunUtils.isSoulbound(ItemStack) now calls isSoulbound(ItemStack, null)

## Related Issues
Resolves #2650

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [x] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/SoulboundListener.java [hunk 1]
```diff
@@ -42,8 +41,8 @@ public void onDamage(PlayerDeathEvent e) {
         for (int slot = 0; slot < p.getInventory().getSize(); slot++) {
             ItemStack item = p.getInventory().getItem(slot);
 
-            // Store soulbound items for later retrieval
-            if (SlimefunUtils.isSoulbound(item)) {
+            // Store soulbound items for later rtrieval
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/SoulboundListener.java:44]: How you butchered this is beyond me.
```suggestion
            // Store soulbound items for later retrieval
```

File: src/main/java/io/github/thebusybiscuit/slimefun4/utils/SlimefunUtils.java [hunk 2]
```diff
@@ -97,23 +112,25 @@ public static boolean isSoulbound(@Nullable ItemStack item) {
             SlimefunItem sfItem = SlimefunItem.getByItem(item);
 
             if (sfItem instanceof Soulbound) {
-                return !sfItem.isDisabled();
+                if (world != null) {
+                    return !sfItem.isDisabled() && !sfItem.isDisabledIn(world);
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/utils/SlimefunUtils.java:116]: I think (you may wanna double-check this) this can be simplified.

```suggestion
                    return !sfItem.isDisabledIn(world);
```

File: src/test/java/io/github/thebusybiscuit/slimefun4/testing/tests/listeners/TestSoulboundListener.java [hunk 3]
```diff
@@ -36,7 +42,7 @@ public static void unload() {
 
     @ParameterizedTest
     @ValueSource(booleans = { true, false })
-    public void testItemDrop(boolean soulbound) {
+    void testItemDrop(boolean soulbound) {
```
Comment (TheBusyBiscuit) [inline src/test/java/io/github/thebusybiscuit/slimefun4/testing/tests/listeners/TestSoulboundListener.java:45]: Can you add an `@DisplayName("...")` annotation to this method?

File: src/test/java/io/github/thebusybiscuit/slimefun4/testing/tests/listeners/TestSoulboundListener.java [hunk 4]
```diff
@@ -50,7 +56,30 @@ public void testItemDrop(boolean soulbound) {
 
     @ParameterizedTest
     @ValueSource(booleans = { true, false })
-    public void testItemRecover(boolean soulbound) {
+    void testItemDropIfItemDisabled(boolean enabled) {
```
Comment (TheBusyBiscuit) [inline src/test/java/io/github/thebusybiscuit/slimefun4/testing/tests/listeners/TestSoulboundListener.java:59]: Can you add an `@DisplayName("...")` annotation to this method?

File: src/test/java/io/github/thebusybiscuit/slimefun4/testing/tests/listeners/TestSoulboundListener.java [hunk 5]
```diff
@@ -50,7 +56,30 @@ public void testItemDrop(boolean soulbound) {
...
+        server.getPluginManager().assertEventFired(EntityDeathEvent.class, event -> {
+            // If the item is enabled, we don't want it to drop.
+            return enabled == !event.getDrops().contains(item);
+        });
+        SlimefunPlugin.getRegistry().getEnabledSlimefunItems().remove(soulboundItem);
+    }
+
+    @ParameterizedTest
+    @ValueSource(booleans = { true, false })
+    void testItemRecover(boolean soulbound) {
```
Comment (TheBusyBiscuit) [inline src/test/java/io/github/thebusybiscuit/slimefun4/testing/tests/listeners/TestSoulboundListener.java:82]: Can you add an `@DisplayName("...")` annotation to this method?

**Review by TheBusyBiscuit — CHANGES_REQUESTED** [review]
Looking pretty good for the most part.

**Review by TheBusyBiscuit — DISMISSED** [review]
LGTM, update changelog too? :eyes:

**Review by TheBusyBiscuit — APPROVED** [review]

**Review by TheBusyBiscuit — APPROVED** [review]

**Review by Sfiguz7 — APPROVED** [review]
1 merge each
