### PR TITLE
Fixes #2509

### LINKED ISSUE #2509: Machines that run at "10x" speed require no energy network
## :round_pushpin: Description (REQUIRED)

The Electric Dust Washer (III) and Electric Gold Pan (III) are fully functional with and without any energy network supplying them power. This is most likely unintended. The other two tiers function as normal for both machines

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

Here is the video proof for both machines, as well as proof that this is an issue with 10x speed machines from other addons, with the example being the Electric Dust Fabricator from Fluffy Machines.
https://streamable.com/jtdud1

## :bulb: Expected behavior (REQUIRED)

I was expecting to supply the required power in order for the Tier III Electric Dust Washer and Electric Gold Pan to work, but found that it nonetheless still converts Sifted Ore into dusts (and Gravel into its outputs) at the same processing speed, 1 op/ 24 gt, which is 10x processing speed, regardless of the presence of an energy network. According to the specs, the tier 3 washer requires 30 J/s and the tier 3 gold pan requires 14 J/s.

## :scroll: Server Log

There are no errors in the server log:
[latest.log](https://github.com/Slimefun/Slimefun4/files/5436127/latest.log)

## :open_file_folder: /error-reports/ Folder

There are no files to upload in that folder.

## :compass: Environment (REQUIRED)

 - Server Software (Spigot/Paper): Paper
 - Minecraft Version: 1.16.3 (stable)
 - Slimefun Version: vDEV - 732
 - CS-CoreLib Version: vDEV - 91

### PR DESCRIPTION
**Pull request by Mooy1**
## Description
AContainers will now check and take charge when they are outputting, not just when progressing.

## Changes
Added a method to check and take the charge ,called it before outputting

## Related Issues
Resolves #2509 

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

**Comment by Mooy1** [comment]
https://streamable.com/7j2z1b vid to show it AContainer still works

File: src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AContainer.java [hunk 1]
```diff
@@ -243,15 +244,16 @@ protected void tick(Block b) {
...
-                    removeCharge(b.getLocation(), getEnergyConsumption());
+                if (!takeCharge(b.getLocation())) {
+                    return;
                 }
+
                 progress.put(b, timeleft - 1);
             } else {
+                if (!takeCharge(b.getLocation())) {
+                    return;
+                }
```
Comment (TheBusyBiscuit) [inline src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AContainer.java:255]: No need for this much nesting and unnecessary guard blocks.

```suggestion
            } else if (takeCharge(b.getLocation())) {
```

File: src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AContainer.java [hunk 2]
```diff
@@ -273,6 +275,17 @@ protected void tick(Block b) {
         }
     }
 
+    protected boolean takeCharge(Location l) {
```
Comment (TheBusyBiscuit) [inline src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AContainer.java:278]: Missing annotation for the parameter.
Also missing javadocs

**Review by TheBusyBiscuit — CHANGES_REQUESTED** [review]

**Comment by Mooy1** [comment]
https://streamable.com/cdxu6z

File: src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AContainer.java [hunk 3]
```diff
@@ -273,6 +274,23 @@ protected void tick(Block b) {
         }
     }
 
+    /**
+     * This method will remove charge from a location if it is chargeable.
+     *
+     * @param l location to try to remove charge from
+     * @return Whether charge was taken if its chargeable
+     */
+    protected boolean takeCharge(@Nonnull Location l) {
```
Comment (TheBusyBiscuit) [inline src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AContainer.java:283]: Since this is a "protected" method, the Non-nullability of this parameter should also be enforced via `Validate.notNull(l, message)`

File: src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AContainer.java [hunk 4]
```diff
@@ -238,31 +240,30 @@ protected void tick(Block b) {
         BlockMenu inv = BlockStorage.getInventory(b);
 
         if (isProcessing(b)) {
-            int timeleft = progress.get(b);
 
-            if (timeleft > 0) {
-                ChestMenuUtils.updateProgressbar(inv, 22, timeleft, processing.get(b).getTicks(), getProgressBar());
+            if (takeCharge(b.getLocation())) {
```
Comment (TheBusyBiscuit) [inline src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AContainer.java:244]: Why was this now placed in front of everything?

**Review by TheBusyBiscuit — CHANGES_REQUESTED** [review]

File: src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AContainer.java (hunk 4 above)
Comment (Mooy1) [reply src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AContainer.java:244]: because it should be called in both cases, so might as well right?

Comment (TheBusyBiscuit) [reply src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AContainer.java:245]: huh, you are right.

**Review by TheBusyBiscuit — APPROVED** [review]

**Review by poma123 — APPROVED** [review]
