### PR TITLE
Fixes #2837

### LINKED ISSUE #2837: Unbreaking III stays "alive" longer than Unbreaking X on tools
## :round_pushpin: Description (REQUIRED)

I crafted two explosive pickaxe.  has Unbreaking III and one have Unbreaking X. It is probably bug, that when I dig with both, The one with Unbreaking III stays "alive" longer, than the one with the Unbreaking X

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1.  Craft e.g. explosive pickaxe and cobalt Pickaxe
2.  Disenchant Unbreaking X from cobalt pickaxe and enchant it into the pickaxe
3.  Craft same explosive pickaxe and enchant it normaly to Unbreaking III

## :bulb: Expected behavior (REQUIRED)

Life time of the tool should be exponencialy growing with higher level of Unbreaking 

## :compass: Environment (REQUIRED)

 - Server Software: 
 - Minecraft Version: 1.16.5
 - Slimefun Version: DEV - 819 (git 854c3335)
versiosf

### PR DESCRIPTION
**Pull request by RobotHanzo**
## Description
This fixes issue #2837

## Changes
The followings are done to fix the issue:
- Changing the way it RNGs to break the item or not, according to the Minecraft Wiki's damage chance on tools (Previously was using the chance for armor)
- Inverted the if statement so it actually fixes #2837

## Demonstration
[YouTube](https://youtu.be/F92LQz02Wko)

## Related Issues
Resolves #2837

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [x] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/armor/ElytraCap.java [hunk 1]
```diff
@@ -41,7 +41,7 @@ public boolean isDamageable() {
     }
 
     @Override
-    public void damageItem(Player p, ItemStack item) {
+    public void damageItem(@Nonnull Player p, ItemStack item) {
```
Comment (WalshyDev) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/armor/ElytraCap.java:44]: nullability for `item` too

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/ClimbingPick.java [hunk 2]
```diff
@@ -235,7 +235,7 @@ private void swing(Player p, Block b, EquipmentSlot hand, ItemStack item) {
     }
 
     @Override
-    public void damageItem(Player p, ItemStack item) {
+    public void damageItem(@Nonnull Player p, ItemStack item) {
```
Comment (WalshyDev) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/ClimbingPick.java:238]: nullability for `item` too

**Review by WalshyDev — CHANGES_REQUESTED** [review]

**Comment by J3fftw1** [comment]
> ## Demonstration
> 
> [YouTube](https://youtu.be/F92LQz02Wko)

This has nothing to do with the PR but i really like how you demonstrate your changes keep up with that! 👍🏽

**Comment by WalshyDev** [comment]
@RobotHanzo not sure if you have done unit testing before but it would be great to have coverage over this class. Especially to prevent issues in the past. Not a requirement but would be great if we could get one :+1: 



> > ## Demonstration
> > [YouTube](https://youtu.be/F92LQz02Wko)
> 
> This has nothing to do with the PR but i really like how you demonstrate your changes keep up with that! 👍🏽

agreed!

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/armor/ElytraCap.java (hunk 1 above)
Comment (RobotHanzo) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/armor/ElytraCap.java:44]: `item` is `Nullable` according to `DamageableItem.java` at line `48`

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/ClimbingPick.java (hunk 2 above)
Comment (RobotHanzo) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/ClimbingPick.java:238]: `item` is `Nullable` according to `DamageableItem.java` at line `48`

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/armor/ElytraCap.java (hunk 1 above)
Comment (WalshyDev) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/armor/ElytraCap.java:44]: So, provide @Nullable

**Comment by RobotHanzo** [comment]
> @RobotHanzo not sure if you have done unit testing before but it would be great to have coverage over this class. Especially to prevent issues in the future. Not a requirement but would be great if we could get one 👍
> 
> > > ## Demonstration
> > > [YouTube](https://youtu.be/F92LQz02Wko)
> > 
> > 
> > This has nothing to do with the PR but i really like how you demonstrate your changes keep up with that! 👍🏽
> 
> agreed!

Haven't done one so this one is the first lmao
If anything looks like 💩 please tell me so I can improve
The tests I pushed have been tested, messing with the code does make it not pass

File: src/test/java/io/github/thebusybiscuit/slimefun4/testing/tests/items/TestDamageableItem.java [hunk 3]
```diff
@@ -0,0 +1,125 @@
...
+    public static void unload() {
+        MockBukkit.unmock();
+    }
+
+    public static DamageableMock getDummyItem(String id, boolean damageable, @Nullable Enchantment enchantment, @Nullable Integer enchantmentLevel) {
+        Category category = TestUtilities.getCategory(plugin, "damageable_item_test");
+        SlimefunItemStack stack = new SlimefunItemStack("DAMAGEABLE_PICKAXE_" + id,
+                Material.DIAMOND_PICKAXE,
+                "&4This pickaxe can break",
+                "&6It appears, it breaks, but most importantly, it tests.");
```
Comment (J3fftw1) [inline src/test/java/io/github/thebusybiscuit/slimefun4/testing/tests/items/TestDamageableItem.java:48]: move ); to new line

**Review by J3fftw1 — CHANGES_REQUESTED** [review]

File: src/test/java/io/github/thebusybiscuit/slimefun4/testing/tests/items/TestDamageableItem.java (hunk 3 above)
Comment (J3fftw1) [inline src/test/java/io/github/thebusybiscuit/slimefun4/testing/tests/items/TestDamageableItem.java:48]:
```suggestion
                "&6It appears, it breaks, but most importantly, it tests."
            );
```

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/staves/StormStaff.java [hunk 4]
```diff
@@ -106,7 +107,7 @@ private void useItem(Player p, ItemStack item, Location loc) {
     }
 
     @ParametersAreNonnullByDefault
```
Comment (J3fftw1) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/staves/StormStaff.java:109]: this can be removed now, right?

**Review by J3fftw1 — CHANGES_REQUESTED** [review]

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/staves/StormStaff.java (hunk 4 above)
Comment (RobotHanzo) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/staves/StormStaff.java]: Nah, shouldn't have added nullable to that item, there are usage right below it

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/staves/StormStaff.java [hunk 5]
```diff
@@ -3,6 +3,7 @@
 import java.util.List;
 
 import javax.annotation.Nonnull;
+import javax.annotation.Nullable;
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/magical/staves/StormStaff.java:6]: Unused import

File: src/test/java/io/github/thebusybiscuit/slimefun4/testing/tests/items/TestDamageableItem.java [hunk 6]
```diff
@@ -0,0 +1,126 @@
...
+            noUnbreakingItem.damageItem(player, xUnbreakingItemIS);
+        }
+        Assertions.assertTrue(noUnbreakingItemIS.hasItemMeta());
+        Assertions.assertTrue(iiiUnbreakingItemIS.hasItemMeta());
+        Assertions.assertTrue(xUnbreakingItemIS.hasItemMeta());
+        Assertions.assertTrue(((Damageable) xUnbreakingItemIS.getItemMeta()).getDamage() < ((Damageable) iiiUnbreakingItemIS.getItemMeta()).getDamage());
+        Assertions.assertTrue(((Damageable) iiiUnbreakingItemIS.getItemMeta()).getDamage() < ((Damageable) noUnbreakingItemIS.getItemMeta()).getDamage());
+    }
+
+    private static class DamageableMock extends SlimefunItem implements DamageableItem {
```
Comment (TheBusyBiscuit) [inline src/test/java/io/github/thebusybiscuit/slimefun4/testing/tests/items/TestDamageableItem.java:107]: Do not declare classes inside of other classes. Make a seperate file for each class.
Check the CONTRIBUTING.md for a reference to our style guidelines.

File: src/main/java/io/github/thebusybiscuit/slimefun4/core/attributes/DamageableItem.java [hunk 7]
```diff
@@ -49,7 +49,7 @@ default void damageItem(@Nonnull Player p, @Nullable ItemStack item) {
         if (isDamageable() && item != null && !item.getType().isAir() && item.getAmount() > 0) {
             int unbreakingLevel = item.getEnchantmentLevel(Enchantment.DURABILITY);
 
-            if (unbreakingLevel > 0 && Math.random() * 100 <= (60 + Math.floorDiv(40, (unbreakingLevel + 1)))) {
+            if (unbreakingLevel > 0 && !(Math.random() < (1.0 / (unbreakingLevel + 1)))) {
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/core/attributes/DamageableItem.java:52]: Now this method is gonna break with any armor items though.
You should probably extract this statement into a dedicated method, so it can be overridden and then provide two constant formaulas for it in our utils package, where it will default to the tools Formula.

**Review by TheBusyBiscuit — CHANGES_REQUESTED** [review]
I assigned myself to this issue for a reason. 
The problem is not that simple so it will still require quite a bit of tweaking.
But thanks for the PR and especially for adding a Unit Test!

File: src/main/java/io/github/thebusybiscuit/slimefun4/utils/UnbreakingRNGUtils.java [hunk 8]
```diff
@@ -0,0 +1,25 @@
...
+import io.github.thebusybiscuit.slimefun4.core.attributes.DamageableItem;
+
+/**
+ * This class is created for a RNG generator to determine if the tool / armor should be damaged when unbreaking enchant is applied.<br>
+ * Mainly used in {@link DamageableItem} and their implementations
+ *
+ * @author RobotHanzo
+ *
+ */
+public class UnbreakingRNGUtils {
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/utils/UnbreakingRNGUtils.java:13]: Also not a fan of this class name really :/

File: src/test/java/io/github/thebusybiscuit/slimefun4/testing/mocks/DamageableMock.java [hunk 9]
```diff
@@ -0,0 +1,32 @@
...
+import me.mrCookieSlime.Slimefun.Objects.SlimefunItem.SlimefunItem;
+import me.mrCookieSlime.Slimefun.api.SlimefunItemStack;
+import org.bukkit.entity.Player;
+import org.bukkit.inventory.ItemStack;
+
+import javax.annotation.Nonnull;
+import javax.annotation.Nullable;
+
+public class DamageableMock extends SlimefunItem implements DamageableItem {
+    boolean itemDamageable;
```
Comment (TheBusyBiscuit) [inline src/test/java/io/github/thebusybiscuit/slimefun4/testing/mocks/DamageableMock.java:16]: Formatting / missing access modifiers

```suggestion

    private final boolean isDamageable;
```

File: src/test/java/io/github/thebusybiscuit/slimefun4/testing/mocks/DamageableMock.java [hunk 10]
```diff
@@ -0,0 +1,32 @@
...
+
+    public DamageableMock(Category category, SlimefunItemStack item, RecipeType recipeType, ItemStack[] recipe, boolean damageable) {
```
Comment (TheBusyBiscuit) [inline src/test/java/io/github/thebusybiscuit/slimefun4/testing/mocks/DamageableMock.java:18]: This can also have a ParametersAreNonnullByDefault annotation

**Review by TheBusyBiscuit — CHANGES_REQUESTED** [review]
Thanks for these quick remarks!
I also got time to finally watch your video on this and wow, I am also amazed by the effort put into this, good job! 👍🏻

File: src/main/java/io/github/thebusybiscuit/slimefun4/core/attributes/DamageableItem.java [hunk 11]
```diff
@@ -69,4 +81,26 @@ default void damageItem(@Nonnull Player p, @Nullable ItemStack item) {
...
+     */
+    default boolean evaluateUnbreakingEnchantment(int unbreakingLevel) {
+        switch (itemType()){
+            case TOOLS:
+                return !(Math.random() < (1.0 / (unbreakingLevel + 1)));
+            case ARMORS:
+                return !(Math.random() < 0.6 + (0.4 / (unbreakingLevel + 1)));
+            default:
+                throw new IllegalArgumentException("itemType must be either UnbreakingAlgorithms.TOOLS or UnbreakingAlgorithms.ARMORS");
+        }
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/core/attributes/DamageableItem.java:103]: This is dead code, an enum is used to ensure that there are only TOOLS or ARMOR as possible types.
A null value would throw a NullPointerException, so this code is never reached.

File: src/main/java/io/github/thebusybiscuit/slimefun4/core/attributes/DamageableItem.java [hunk 12]
```diff
@@ -69,4 +81,26 @@ default void damageItem(@Nonnull Player p, @Nullable ItemStack item) {
...
+     *                                 Thrown when {@link #itemType()} doesn't return a valid {@link UnbreakingAlgorithms} value
+     * @return Whether you should keep the item undamaged
+     *
+     */
+    default boolean evaluateUnbreakingEnchantment(int unbreakingLevel) {
+        switch (itemType()){
+            case TOOLS:
+                return !(Math.random() < (1.0 / (unbreakingLevel + 1)));
+            case ARMORS:
+                return !(Math.random() < 0.6 + (0.4 / (unbreakingLevel + 1)));
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/core/attributes/DamageableItem.java:100]: I think that these formulas should rather be stored inside the respective enum constant instead of relying on a switch/case here.

File: src/main/java/io/github/thebusybiscuit/slimefun4/core/attributes/DamageableItem.java [hunk 13]
```diff
@@ -34,22 +35,33 @@
...
+    /**
+     * Change this to a {@link UnbreakingAlgorithms} value if needed to fit the type of the damageable item
+     * Defaults to return {@link UnbreakingAlgorithms#TOOLS},
+     * which represents {@link DamageableItem} utilizes the tool algorithm to determine the chance of item damaging
+     *
+     * @return The {@link UnbreakingAlgorithms} of the itemType
+     */
+    default UnbreakingAlgorithms itemType() {
+        return UnbreakingAlgorithms.TOOLS;
+    }
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/core/attributes/DamageableItem.java:47]: I don't think we need this method here

File: src/main/java/io/github/thebusybiscuit/slimefun4/utils/UnbreakingAlgorithms.java [hunk 14]
```diff
@@ -0,0 +1,15 @@
...
+
+/**
+ * This a enum indicating if a {@link DamageableItem} is a tool or an armor
+ * This effects the way they determine if an item should be damaged
+ *
+ * @author RobotHanzo
+ */
+public enum UnbreakingAlgorithms {
+    TOOLS,
+    ARMORS
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/utils/UnbreakingAlgorithms.java:14]:
```suggestion
    ARMOR;
```

File: src/main/java/io/github/thebusybiscuit/slimefun4/utils/UnbreakingAlgorithms.java [hunk 15]
```diff
@@ -0,0 +1,15 @@
...
+
+import io.github.thebusybiscuit.slimefun4.core.attributes.DamageableItem;
+
+/**
+ * This a enum indicating if a {@link DamageableItem} is a tool or an armor
+ * This effects the way they determine if an item should be damaged
+ *
+ * @author RobotHanzo
+ */
+public enum UnbreakingAlgorithms {
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/utils/UnbreakingAlgorithms.java:12]: Also enums should be in singular, not plural form.

```suggestion
public enum UnbreakingAlgorithm {
```

File: src/main/java/io/github/thebusybiscuit/slimefun4/core/attributes/DamageableItem.java (hunk 12 above)
Comment (TheBusyBiscuit) [reply src/main/java/io/github/thebusybiscuit/slimefun4/core/attributes/DamageableItem.java:100]: THen we could simplify:

```java
default boolean evaluateUnbreakingEnchantment(int unbreakingLevel) {
    return UnbreakingAlgorithm.TOOLS.evaluate(unbreakingLevel);
}
```

**Review by TheBusyBiscuit — CHANGES_REQUESTED** [review]

File: src/main/java/io/github/thebusybiscuit/slimefun4/core/attributes/DamageableItem.java (hunk 11 above)
Comment (RobotHanzo) [reply src/main/java/io/github/thebusybiscuit/slimefun4/core/attributes/DamageableItem.java:103]: My IDE would raise an error if I didn't put that

File: src/main/java/io/github/thebusybiscuit/slimefun4/utils/UnbreakingAlgorithm.java [hunk 16]
```diff
@@ -0,0 +1,26 @@
...
+            return !(Math.random() < (1.0 / (unbreakingLevel + 1)));
+        }
+
+        if (this == ARMOR) {
+            return !(Math.random() < 0.6 + (0.4 / (unbreakingLevel + 1)));
+        }
+
+        return false;
+    }
+}
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/utils/UnbreakingAlgorithm.java:26]: Reyling on if-statements here is not really ideal.
We can just pass the method as a lambda expression in the constructor like this:

```suggestion
public enum UnbreakingAlgorithm {

    ARMOR(lvl -> !(Math.random() < 0.6 + (0.4 / (unbreakingLevel + 1))),
    TOOLS(lvl -> !(Math.random() < (1.0 / (lvl + 1))));

    private final IntFunction<Boolean> function;
    
    UnbreakingAlgorithm(@Nonnull IntFunction<Boolean> function) {
        this.function = function;
    }

    public boolean evaluate(int unbreakingLevel) {
        return function.apply(unbreakingLevel);
    }
}
```

**Review by TheBusyBiscuit — CHANGES_REQUESTED** [review]
One last improvement, otherwise it is looking really good!

Thanks for putting this much effort into it and for bearing all my nitpicky reviews ❤️ 
Much appreciated!

File: src/main/java/io/github/thebusybiscuit/slimefun4/core/attributes/DamageableItem.java (hunk 11 above)
Comment (WalshyDev) [reply src/main/java/io/github/thebusybiscuit/slimefun4/core/attributes/DamageableItem.java]: Defaults should always be there. People can still technically inject into enums, new things can be aded, etc. It's good practice to include it.

SonarLint must complain if it doesn't have it, no?

**Comment by RobotHanzo** [comment]
Just tested this with fluffy's upgraded explosive picks, it works.

**Comment by TheBusyBiscuit** [comment]
Oh yeah I forgot the import

**Comment by RobotHanzo** [comment]
> Oh yeah I forgot the import

Doing it now

**Comment by RobotHanzo** [comment]
Going to test it for the last time

**Review by TheBusyBiscuit — APPROVED** [review]
Looks good to me.

Only thing I still find a little bit confusing is finding out what the boolean stands, whether we should even negate it at all and what not.
But that is probably a discussion for another day.
A ton of effort was put into this and we appreciate it a lot. ❤️ 

Any remarks on your side left? @WalshyDev

**Comment by RobotHanzo** [comment]
Last test worked.

**Review by WalshyDev — APPROVED** [review]
LGTM
