### PR TITLE
Deobfuscate blocks when gold panning

### LINKED ISSUE #3764: Gold pan & Nether Gold Pan
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

With Orebfuscator installed and running, using a gold pan or nether gold pan will leave behind obfuscated ores and not clean up like it's meant to.

### 📑 Reproduction Steps

1. Install Orebfuscator and Slimefun
2. Get a gold pan or nether gold pan
3. Use either on respective blocks
4. Take note of obfuscated blocks not updating to show the real block.

### 💡 Expected Behavior

I expect the breaking event from gold pan and nether gold pan to update the surrounding blocks.

### 📜 Server Log

No errors occur in console.

### 📂 `/error-reports/` folder

No error reports in directory.

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

Screenshot from 2023-02-08 15-14-23

### 🧭 Other plugins

Related to Orebfuscator

### PR DESCRIPTION
**Pull request by iTwins**
## Description

When using the gold pan with orebfuscator it doesn't update the obfuscated blocks

## Proposed changes

Add an event handler for the gold pan to ``OrebfuscatorIntegration.java`` that deobfuscates the blocks

## Related Issues (if applicable)

Resolves #3764

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I have made sure that the proposed changes do not break compatibility across the supported Minecraft versions (1.16.* - 1.20.*).
- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

**Review by J3fftw1 — APPROVED** [review]

**Review by JustAHuman-xD — APPROVED** [review]
LGTM just needs tested

File: src/main/java/io/github/thebusybiscuit/slimefun4/integrations/OrebfuscatorIntegration.java [hunk 1]
```diff
@@ -61,4 +64,14 @@ public void onExplosiveToolBreakBlocks(ExplosiveToolBreakBlocksEvent event) {
...
+
+    @EventHandler(priority = EventPriority.MONITOR, ignoreCancelled = true)
+    public void onGoldPanUse(PlayerRightClickEvent event) {
+        if (event.getSlimefunItem().isPresent() && event.getClickedBlock().isPresent()) {
+            String id = event.getSlimefunItem().get().getId();
+            if (id.equals(SlimefunItems.GOLD_PAN.getItemId()) || id.equals(SlimefunItems.NETHER_GOLD_PAN.getItemId())) {
+                this.service.deobfuscate(List.of(event.getClickedBlock().get()));
+            }
+        }
+    }
```
Comment (JustAHuman-xD) [inline src/main/java/io/github/thebusybiscuit/slimefun4/integrations/OrebfuscatorIntegration.java:76]: I would replace this with an instanceof GoldPan check, so `event.getSlimefunItem().get() instanceof GoldPan`

Comment (iTwins) [reply src/main/java/io/github/thebusybiscuit/slimefun4/integrations/OrebfuscatorIntegration.java]: Smart, changed now

File: src/main/java/io/github/thebusybiscuit/slimefun4/integrations/OrebfuscatorIntegration.java [hunk 2]
```diff
@@ -61,4 +64,13 @@ public void onExplosiveToolBreakBlocks(ExplosiveToolBreakBlocksEvent event) {
     public void onReactorExplode(ReactorExplodeEvent event) {
         this.service.deobfuscate(Arrays.asList(event.getLocation().getBlock()));
     }
+
+    @EventHandler(priority = EventPriority.MONITOR, ignoreCancelled = true)
+    public void onGoldPanUse(PlayerRightClickEvent event) {
+        if (event.getSlimefunItem().isPresent() && event.getClickedBlock().isPresent()) {
+            if (event.getSlimefunItem().get() instanceof GoldPan) {
```
Comment (J3fftw1) [inline src/main/java/io/github/thebusybiscuit/slimefun4/integrations/OrebfuscatorIntegration.java:71]: these ifs can now be combined as well

**Review by J3fftw1 — CHANGES_REQUESTED** [review]

File: src/main/java/io/github/thebusybiscuit/slimefun4/integrations/OrebfuscatorIntegration.java (hunk 2 above)
Comment (iTwins) [reply src/main/java/io/github/thebusybiscuit/slimefun4/integrations/OrebfuscatorIntegration.java]: Fixed

**Review by J3fftw1 — APPROVED** [review]

**Comment by variananora** [comment]
Tested this on 1.20.1 with Orebfuscator 5.4.0 and it works flawlessly.

**Review by JustAHuman-xD — APPROVED** [review]
LGTM 👍
