### PR TITLE
Fix multiple Book Binder issues.

### LINKED ISSUE #2805: Book binder is not working as intended.
## :round_pushpin: Description (REQUIRED)
The book binder is not combining the higher of the enchantments on the books to the final product, it is simply duplicating the enchantments of the book placed in the left side of the input.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1.  Place a book with Eff V/Fortune1 on the left and  Eff1/Fortune3 on the right. It gives you Eff V / Fortune 1 
2. Place a book with Eff 1 / Fortune3 on the left and Eff V / Fortune 1 on the right, it simply duplicated the left book and gave me Eff1/fortune 3 as the result.

## :bulb: Expected behavior (REQUIRED)

I was expecting the higher of the enchants from each book to end up on the finished book, but that did not happen, it's simply duplicating the left most book enchants.

## :scroll: Server Log

no logs.

## :open_file_folder: /error-reports/ Folder

no errors.

## :compass: Environment (REQUIRED)

image

I am currently running the server with no CS-CoreLib.

### PR DESCRIPTION
**Pull request by ProfElements**
## Description

Fix Multiple issues with the bookbinder, including but not limited to:

Overleveled echantments (ex Unbreaking 6) does not disappearing off combined book instead reverts to maximum vanilla level unless ItemSetting is set and Make sure the player never gets a no enchantment enchanted book. 
## Changes

Made BookBinder confirm that the enchanted book never has no enchants. Make sure the book binder doesnt recklessly destroy enchants that are overleveled. Make sure the BookBinder handles overleveled enchantments correctly. 

## Related Issues

Resolves #2805 
## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/BookBinder.java [hunk 1]
```diff
@@ -110,13 +114,23 @@ public String getMachineIdentifier() {
...
 
             if (!conflicts) {
                 enchantments.merge(entry.getKey(), entry.getValue(), (a, b) -> {
+                    int enchantMaxLevel = entry.getKey().getMaxLevel();
+
                     if (a.intValue() == b.intValue()) {
+                        if (enchantMaxLevel <= a) { 
+                            return enchantMaxLevel;
+                        }
                         if (hasCustomMaxLevel.getValue()) {
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/BookBinder.java:134]:
```suggestion
                        if (enchantMaxLevel <= a) { 
                            return enchantMaxLevel;
                        }
                        else if (hasCustomMaxLevel.getValue()) {
```

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/BookBinder.java [hunk 2]
```diff
@@ -110,13 +114,23 @@ public String getMachineIdentifier() {
         for (Map.Entry<Enchantment, Integer> entry : ech2.entrySet()) {
             for (Map.Entry<Enchantment, Integer> conflictsWith : enchantments.entrySet()) {
                 if (entry.getKey().conflictsWith(conflictsWith.getKey())) {
-                    conflicts = true;
+                    if (entry.getKey() == conflictsWith.getKey()) { 
+
+                    } else {
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/BookBinder.java:119]: Why is there an empty if-block here?

**Review by TheBusyBiscuit — CHANGES_REQUESTED** [review]
Also please add documentation and comments where possible, so these changes are easier to follow and understand

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/BookBinder.java (hunk 2 above)
Comment (ProfElements) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/BookBinder.java:119]: having the same key as between entry and conflictsWith that is overleveled (ex unbreaking 6) still makes conflictsWith = true

Comment (ProfElements) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/BookBinder.java:119]: so that is set their just in case, it can probably be moved into the higher if block

Comment (WalshyDev) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/BookBinder.java:119]: that doesn't answer why there's an empty if. Just negate (but also don't create an inner-if for no reason)

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/BookBinder.java [hunk 3]
```diff
@@ -109,23 +114,36 @@ public String getMachineIdentifier() {
...
+                    int enchantMaxLevel = entry.getKey().getMaxLevel();
+
                     if (a.intValue() == b.intValue()) {
-                        if (hasCustomMaxLevel.getValue()) {
+                        
+                        //Confirm the entries enchant level doesnt  go over the maximums unless it uses bypass-vanilla-max-level
+                        if (enchantMaxLevel <= a && !bypassVanillaMaxLevel.getValue()) { 
+                            return enchantMaxLevel;
+                        }
+                        else if (hasCustomMaxLevel.getValue()) {
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/BookBinder.java:134]:
```suggestion
                        } else if (hasCustomMaxLevel.getValue()) {
```

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/BookBinder.java [hunk 4]
```diff
@@ -109,23 +114,36 @@ public String getMachineIdentifier() {
...
                         }
                     } else {
                         int highestLevel = Math.max(a, b);
 
-                        if (hasCustomMaxLevel.getValue()) {
+                        //Confirm the entries enchant level doesnt  go over the maximums unless it uses bypass-vanilla-max-level
+                        if (enchantMaxLevel <= highestLevel && !bypassVanillaMaxLevel.getValue()) {
+                            return enchantMaxLevel;
+                        }
+                         else if (hasCustomMaxLevel.getValue()) {
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/BookBinder.java:146]:
```suggestion
                        } else if (hasCustomMaxLevel.getValue()) {
```

**Review by TheBusyBiscuit — CHANGES_REQUESTED** [review]
some formatting mistakes, otherwise looking good as far as I can tell

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/BookBinder.java [hunk 5]
```diff
@@ -109,23 +115,34 @@ public String getMachineIdentifier() {
 
         for (Map.Entry<Enchantment, Integer> entry : ech2.entrySet()) {
             for (Map.Entry<Enchantment, Integer> conflictsWith : enchantments.entrySet()) {
-                if (entry.getKey().conflictsWith(conflictsWith.getKey())) {
-                    conflicts = true;
+
+                //Check if entry enchantments and conflictsWith enchantment conflict, and confirms that the enchantsments aren't the exact same.
+                if (entry.getKey().conflictsWith(conflictsWith.getKey()) && entry.getKey() != conflictsWith.getKey()) {
+                        conflicts = true;
                 }
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/BookBinder.java:122]: `!=` should never be used to compare objects, only for primitives.

```suggestion
                // Check if entry enchantments and conflictsWith enchantment conflict, and confirms that the enchantsments aren't the exact same.
                if (entry.getKey().conflictsWith(conflictsWith.getKey()) && Objects.equals(entry.getKey(), conflictsWith.getKey())) {
                    conflicts = true;
                }
```

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/BookBinder.java [hunk 6]
```diff
@@ -109,23 +115,34 @@ public String getMachineIdentifier() {
...
             }
 
             if (!conflicts) {
                 enchantments.merge(entry.getKey(), entry.getValue(), (a, b) -> {
+                    int enchantMaxLevel = entry.getKey().getMaxLevel();
+
                     if (a.intValue() == b.intValue()) {
-                        if (hasCustomMaxLevel.getValue()) {
+                        
+                        //Confirm the entries enchant level doesnt  go over the maximums unless it uses bypass-vanilla-max-level
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/BookBinder.java:131]:
```suggestion
                        // Confirm the entries enchant level doesn't go over the maximums unless it uses bypass-vanilla-max-level
```

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/BookBinder.java [hunk 7]
```diff
@@ -109,23 +115,34 @@ public String getMachineIdentifier() {
...
+                        } else if (hasCustomMaxLevel.getValue()) {
                             return a + 1 > customMaxLevel.getValue() ? customMaxLevel.getValue() : a + 1;
                         } else {
                             return a + 1;
                         }
                     } else {
                         int highestLevel = Math.max(a, b);
 
-                        if (hasCustomMaxLevel.getValue()) {
+                        //Confirm the entries enchant level doesnt  go over the maximums unless it uses bypass-vanilla-max-level
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/BookBinder.java:142]:
```suggestion
                        // Confirm the entries enchant level doesn't go over the maximums unless it uses bypass-vanilla-max-level
```

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/BookBinder.java [hunk 8]
```diff
@@ -63,6 +64,11 @@ protected MachineRecipe findNextRecipe(BlockMenu menu) {
                         enchantMeta.addStoredEnchant(entry.getKey(), entry.getValue(), bypassVanillaMaxLevel.getValue());
                     }
 
+                    //Make sure we never return a no enchant enchanted book.
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/BookBinder.java:67]:
```suggestion
                    // Make sure we never return an enchanted book without any enchantments.
```

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/BookBinder.java [hunk 9]
```diff
@@ -54,6 +54,7 @@ protected MachineRecipe findNextRecipe(BlockMenu menu) {
                 Map<Enchantment, Integer> storedTargetEnchantments = targetMeta.getStoredEnchants();
                 Map<Enchantment, Integer> enchantments = combineEnchantments(storedItemEnchantments, storedTargetEnchantments);
 
+                //just return if enchantments are none. shouldnt ever happen. :NotLikeThis:
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/BookBinder.java:57]:
```suggestion
                // Just return if no enchantments exist. This shouldn't ever happen. :NotLikeThis:
```

**Review by TheBusyBiscuit — CHANGES_REQUESTED** [review]
Some docs improvements / typo fixes.
But mainly the key comparison needed to be fixed.

**Review by TheBusyBiscuit — APPROVED** [review]

**Review by Sfiguz7 — APPROVED** [review]
LGTM
