### PR TITLE
Move PlayerProfile saving off the main thread

### LINKED ISSUE #4118: move auto saves from main thread to off thread
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

See the discord thread below

https://discord.com/channels/565557184348422174/565569196218384385/1203819747687268403

and walshy's notes

https://discord.com/channels/565557184348422174/565569196218384385/1203820974470860893

### 📑 Reproduction Steps

review the spark report linked above

### 💡 Expected Behavior

moving save to off the main thread to reduce lag when saving

### 📷 Screenshots / Videos

_No response_

### 📜 Server Log

none

### 📂 `/error-reports/` folder

none

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

1133

### 🧭 Other plugins

_No response_

### PR DESCRIPTION
**Pull request by WalshyDev**
## Description
Moves the PlayerProfile saving off the main thread

## Proposed changes
Move PlayerProfile off main thread, add debugs and improve tab completion for debug

Moved the PlayerProfile saving off the main thread, we generally load this off-thread but now we also save off-thread. I thought we were already doing this but apparently not, especially with our current YAML stuff this should definitely be done

Also done a small change to ensure that we don't remove the PlayerProfile from memory if the player is still online. I don't think we ever had a reported issue from this but it's kinda weird behaviour

Finally, added some debug logs to the saving logic, this can be enabled with `/sf debug slimefun_player_profile_data`. Also added auto-complete to /sf debug because it's nice, this only works for Slimefun test cases rather than addons but that's fine. Mostly internal anyway

---

**Please consider any cases where this will cause issues and bring them up!**

I think this should be generally safe since we've been saving on-thread but loading off-thread anyway for ages but we should exercise caution. I think with the extra enforcement of the player definitely still being offline there's no issue here but give it a think before approving :)

## Related Issues (if applicable)
Resolves #4118 

## Checklist
- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I have made sure that the proposed changes do not break compatibility across the supported Minecraft versions (1.16.* - 1.20.*).
- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

**Comment by WalshyDev** [comment]
I tested a basic profile with just researches and with research + backpacks (both Slimefun items and vanilla). Each one could save without issue

**Review by J3fftw1 — DISMISSED** [review]

File: src/main/java/io/github/thebusybiscuit/slimefun4/api/player/PlayerProfile.java [hunk 1]
```diff
@@ -237,13 +238,15 @@ public void removeWaypoint(@Nonnull Waypoint waypoint) {
...
     public final void markForDeletion() {
+        Debug.log(TestCase.PLAYER_PROFILE_DATA, "Marking {} ({}) profile for deletion", name, ownerId);
         markedForDeletion = true;
     }
 
     /**
      * Call this method if this Profile has unsaved changes.
      */
     public final void markDirty() {
+        Debug.log(TestCase.PLAYER_PROFILE_DATA, "Marking {} ({}) profile as diry", name, ownerId);
```
Comment (Sfiguz7) [inline src/main/java/io/github/thebusybiscuit/slimefun4/api/player/PlayerProfile.java:249]:
```suggestion
        Debug.log(TestCase.PLAYER_PROFILE_DATA, "Marking {} ({}) profile as dirty", name, ownerId);
```

**Review by Sfiguz7 — APPROVED** [review]
Can't think of a case in which this would fail if the original worked so LGTM

**Review by J3fftw1 — APPROVED** [review]
