### PR TITLE
Fixes ArmorForge

### LINKED ISSUE #2469: Unable to craft Elytra Cap without an Output Chest
## :round_pushpin: Description
When attempting to craft Elytra Cap in an Armor Forge, it writes "Inventory full", despite the fact that the slots would clear after consuming the materials. This is fixed when you put an output chest next to it as it gives it a free slot for output.

## :bookmark_tabs: Steps to reproduce the Issue
1. Attempt to craft Elytra Cap.
2. Fail

## :bulb: Expected behavior
Materials should be consumed and the Elytra Cap should appear in the dispenser of an Armor Forge

## :scroll: Server Log
None

## :open_file_folder: /error-reports/ Folder
None

## :compass: Environment (REQUIRED)
image

### PR DESCRIPTION
**Pull request by CURVX**
## Description

#2469 Crafted Elytra Cap in ArmorForge
https://streamable.com/p28b4f

## Changes

Made `ArmorForge` extend `BackpackCrafter` instead of `MultiBlockMachine`
Used `EnchancedCraftingTable.java` as Reference to make further changes

## Related Issues

Resolves #2469 

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/ArmorForge.java [hunk 1]
```diff
@@ -71,26 +66,51 @@ private boolean isCraftable(Inventory inv, ItemStack[] recipe) {
...
+
+            fakeInv.setItem(j, stack);
         }
 
-        for (int j = 0; j < 4; j++) {
-            int current = j;
+        return fakeInv;
+    }
+
+    private void craft(Player p, ItemStack output, Inventory inv, Block dispenser) {
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/ArmorForge.java:86]: This could use some annotations.

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/ArmorForge.java [hunk 2]
```diff
@@ -71,26 +66,51 @@ private boolean isCraftable(Inventory inv, ItemStack[] recipe) {
...
+                ItemUtils.consumeItem(stack, true);
             }
+
+            fakeInv.setItem(j, stack);
         }
 
-        for (int j = 0; j < 4; j++) {
-            int current = j;
+        return fakeInv;
+    }
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/ArmorForge.java:84]: Is this method copied from anywhere?
I think it would make sense to make it a static utility method or so since we would otherwise face a lot of redundancies and duplications.

**Review by TheBusyBiscuit — CHANGES_REQUESTED** [review]

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/ArmorForge.java (hunk 2 above)
Comment (CURVX) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/ArmorForge.java:84]: > Is this method copied from anywhere?

Yes, from BackpackCrafter: https://github.com/Slimefun/Slimefun4/blob/c9adba2f39068490518bafe0cb8fd9bc04a7b572/src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/BackpackCrafter.java#L43

How do I tackle this? Make `ArmorForge extends BackpackCrafter` instead of MultiBlockMachine since latter is already extended in BackpackCrafter. Sorry. I know its messy but I am learning and loving it so far :D

Comment (TheBusyBiscuit) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/ArmorForge.java:84]: I think making it extend BackpackCrafter should be fine, even though the BackpackCrafter class might need a new name after this XD

**Review by TheBusyBiscuit — APPROVED** [review]

**Review by poma123 — APPROVED** [review]
LGTM
