### PR TITLE
Fixes #4087 and some cleanup

### LINKED ISSUE #4087: You can take items out of Menus after Breaking a Block
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

There has been a long standing bug and known dupe using InfinityExpansion where you have two people, one person breaks a storage container and the other takes items out of it while they do so. There is a small period of time where you can take out items after the item has been dropped, effectively duping the Items. 

I suspect the cause is the one tick delay before blockstorage is cleared after a block is broken. So after its broken but before blockstorage is cleared there is a period of time to take out items. Theoretically this should be possible with any menus but its easy for IE because of the buttons to easily take out items. The laggier the server the easier it is to achieve.

When I get out of school ill attach more information but other than description and steps I can’t give much right now.

### 📑 Reproduction Steps

1. Find someone to help you
2. Place a Storage Container filled with Items
3. Have one person break the storage container and the other open it and spam the button to take out items
4. See if you were successful, if not goto step 2

### 💡 Expected Behavior

After breaking the block the menu should be “broken” too. It should not be able to be opened, interacted with, or remain open, etc.

### 📷 Screenshots / Videos

(When I get out of school I’ll add a video if I can)

### 📜 Server Log

_No response_

### 📂 `/error-reports/` folder

_No response_

### 💻 Server Software

Spigot (Is not software dependent)

### 🎮 Minecraft Version

1.20.x (But is not version dependent)

### ⭐ Slimefun version

Dev 1123 (But it works on every build afaik)

### 🧭 Other plugins

_No response_

### PR DESCRIPTION
**Pull request by WalshyDev**
## Description
Per #4087 if you can get into the inventory of a broken block you can easily dupe items (take them out of the inv before cleanup - 500ms by default and from block drops).
We want to fix that and there's also just some general cleanup

## Proposed changes
There are 2 parts to this fix, the first is disabling opening the inventory if the block is broken. The second is closing the inventory on block create (rather than an SF tick later). Created a pretty long test to validate this behaviour and fully verified it through debugger.

I also did a bit of cleanup, and commented out `checkForSensitiveBlocks` rather than the code in the function so we don't have random unused code. Moved @Nonnull annotations in BiomeMap as vscode was freaking out over it being in the middle of generics.

## Related Issues (if applicable)
Fixes #4087 

## Checklist
- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I have made sure that the proposed changes do not break compatibility across the supported Minecraft versions (1.16.* - 1.20.*).
- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [x] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

**Comment by WalshyDev** [comment]
cc: @JustAHuman-xD

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockListener.java [hunk 1]
```diff
@@ -220,6 +221,14 @@ private void callBlockHandler(BlockBreakEvent e, ItemStack item, List<ItemStack>
...
             drops.addAll(sfItem.getDrops());
+            // Partial fix for #4087 - We don't want the inventory to be usable post break, close it for anyone still inside
+            // The main fix is in SlimefunItemInteractListener preventing opening to begin with
+            // Close the inventory for all viewers of this block
+            // TODO(future): Remove this check when MockBukkit supports viewers
+            if (!Slimefun.instance().isUnitTest()) {
+                BlockStorage.getInventory(e.getBlock()).toInventory().getViewers().forEach(HumanEntity::closeInventory);
+            }
+            // Remove the block data
             BlockStorage.clearBlockInfo(e.getBlock());
```
Comment (JustAHuman-xD) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockListener.java:232]: I will say this scares me 😅 sense this just kinda goes around the existing one tick delay that we don't know the reason behind existing

Comment (WalshyDev) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockListener.java:232]: huh? This is existing code, this is how we remove the data on break (which triggers the cleanup a tick later). This is normal?

File: src/main/java/io/github/thebusybiscuit/slimefun4/utils/biomes/BiomeMap.java [hunk 2]
```diff
@@ -140,25 +140,28 @@ public String toString() {
...
-    public static <T> @Nonnull BiomeMap<T> fromJson(NamespacedKey key, String json, BiomeDataConverter<T> valueConverter, boolean isLenient) throws BiomeMapException {
+    public static <T> BiomeMap<T> fromJson(NamespacedKey key, String json, BiomeDataConverter<T> valueConverter, boolean isLenient) throws BiomeMapException {
         // All parameters are validated by the Parser.
         BiomeMapParser<T> parser = new BiomeMapParser<>(key, valueConverter);
         parser.setLenient(isLenient);
         parser.read(json);
         return parser.buildBiomeMap();
     }
 
+    @Nonnull
```
[the remark this answers is not in the document]
Comment (WalshyDev) [reply src/main/java/io/github/thebusybiscuit/slimefun4/utils/biomes/BiomeMap.java:162]: Yes but it's also messy as it was before along with just throwing syntax errors in other editors.

[the remark this answers is not in the document]
Comment (J3fftw1) [reply src/main/java/io/github/thebusybiscuit/slimefun4/utils/biomes/BiomeMap.java:162]: Everyone hates the inline stuff anyways.
We might need to rethink this.

**Review by J3fftw1 — APPROVED** [review]
I would like this to be tested but this is an annoying thing to be tested.
But there is unit tests so LGTM

**Review by Sfiguz7 — APPROVED** [review]

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockListener.java (hunk 1 above)
Comment (JustAHuman-xD) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockListener.java:232]: Ah I misunderstood, mb, review on my phone at like midnight 💀
