### PR TITLE
Fix disappearing items with output chest by machines

### LINKED ISSUE #3136: Items processed by compressor will disappear when output chest is going to full
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When output chest is going to full(not full yet) and compressor is processing items more than output chest can store, the rest of items that processed will disappear. But if output chest already full, and compressor is processing items, the items will go to compressor instead

### 📑 Reproduction Steps

1. Fill output chest with items(in this case, example: carbon) until almost full
2. Get coal block more than enough for crafting carbon
3. Right click the compressor

### 💡 Expected Behavior

When output chest is full and the compressor is still processing, the items will go to compressor.

### 📷 Screenshots / Videos

While output chest isnt full
https://user-images.githubusercontent.com/70990197/123103125-e8f0aa00-d45f-11eb-88b0-3ab44fee5bcc.mp4

While output chest is already full
https://user-images.githubusercontent.com/70990197/123103231-fe65d400-d45f-11eb-93b0-ba87bbab056b.mp4

### 📜 Server Log

_No response_

### 📂 `/error-reports/` folder

_No response_

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.16.x

### ⭐ Slimefun version

DEV- 939 (git 57f7553f)
image

### 🧭 Other plugins

_No response_

### PR DESCRIPTION
**Pull request by EpicPlayerA10**
## Description
This fixes disappearing items with machines connected to almost full output chest.
These machines are: Compressor, Magic Workbench, Armor Forge, Pressure Chamber.

## Proposed changes
Added to `Compressor`, `MagicWorkbench`, `ArmorForge` and `PressureChamber` check if the items can be added to the output chest after crafting.
If items can't be added then item will be added to another output chest (if it exists). And if items can't be added to any output chests then item will be added to dispenser. And if item can't be added to dispenser then the item will drop on the ground.

## Related Issues (if applicable)

Resolves #3136 

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

**Comment by J3fftw1** [comment]
> The `InvUtils` import stmt belongs lower (with the other io.xxx stuff). Other than that, the 'play sound' happens in every branch (other than the timing one) and therefore could be extracted but it might not be necessary, just thought I'd mention it.
> 
> You could also try to find another output chest if the output does not fit into the one that was found before the crafting process started (there can be more than 1 afaik).

Im in favor of extracting it since people that have addons with multi blocks can also easily adjust then. (I wont need to copy over this method then since all multiblock crafting will have this issue)

**Comment by EpicPlayerA10** [comment]
> 
> 
> The `InvUtils` import stmt belongs lower (with the other io.xxx stuff). Other than that, the 'play sound' happens in every branch (other than the timing one) and therefore could be extracted but it might not be necessary, just thought I'd mention it.
> 
> You could also try to find another output chest if the output does not fit into the one that was found before the crafting process started (there can be more than 1 afaik).

I thought about items will be added to another output chest but i need to modify `findOutputChestFor` method in `OutputChest` class. And i think it could break some other machines.

**Comment by martinbrom** [comment]
> I thought about items will be added to another output chest but i need to modify `findOutputChestFor` method in `OutputChest` class. And i think it could break some other machines.

why not just call it again? it won't return the original once since the items won't fit into that one

**Comment by EpicPlayerA10** [comment]
> why not just call it again? it won't return the original output chest since the items won't fit into that one

Hmm, wait a second

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/ArmorForge.java [hunk 1]
```diff
@@ -90,8 +91,16 @@ private void craft(Player p, ItemStack output, Inventory inv, Block dispenser) {
                     if (current < 3) {
                         p.getWorld().playSound(p.getLocation(), Sound.BLOCK_ANVIL_USE, 1F, 2F);
                     } else {
+                        Inventory outputInv2 = findOutputInventory(output, dispenser.getBlock(), dispenser.getInventory());
                         p.getWorld().playSound(p.getLocation(), Sound.ENTITY_ARROW_HIT_PLAYER, 1F, 1F);
-                        outputInv.addItem(output);
+                        if (outputInv2 != null) {
+                            outputInv2.addItem(output);
+                        } else if (InvUtils.fits(dispenser.getInventory(), output)) {
```
Comment (WalshyDev) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/ArmorForge.java:98]: You should cache these getInventory calls, it will make a new one every time.

(ref: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/src/main/java/org/bukkit/craftbukkit/block/CraftDispenser.java#30-37)

**Review by WalshyDev — CHANGES_REQUESTED** [review]

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/ArmorForge.java (hunk 1 above)
Comment (EpicPlayerA10) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/ArmorForge.java]: okay

**Review by TheBusyBiscuit — CHANGES_REQUESTED** [review]
This all seems like a lot of duplicated code to me, might be worth to create a method in the super class and just call that

**Comment by EpicPlayerA10** [comment]
> This all seems like a lot of duplicated code to me, might be worth to create a method in the super class and just call that

Better?

File: src/main/java/io/github/thebusybiscuit/slimefun4/core/multiblocks/MultiBlockMachine.java [hunk 2]
```diff
@@ -165,6 +165,29 @@ public void load() {
...
+    /**
+     * This method handles a output {@link ItemStack} from the {@link MultiBlockMachine} which has a crafting delay
+     *
+     * @param outputItem
+     *          A crafted {@link ItemStack} from {@link MultiBlockMachine}
+     * @param dispenser
+     *          Our {@link Dispenser} from {@link MultiBlockMachine}
+     *
+     */
+    protected void handleCraftedItem(ItemStack outputItem, Dispenser dispenser) {
```
Comment (WalshyDev) [inline src/main/java/io/github/thebusybiscuit/slimefun4/core/multiblocks/MultiBlockMachine.java:177]: I would prefer we use `Container` instead of `Dispenser`. I don't see a reason to limit this to ONLY dispensers. This could easily be a chest, trapped chest, furnace even.

**Review by WalshyDev — CHANGES_REQUESTED** [review]

File: src/main/java/io/github/thebusybiscuit/slimefun4/core/multiblocks/MultiBlockMachine.java (hunk 2 above)
Comment (EpicPlayerA10) [reply src/main/java/io/github/thebusybiscuit/slimefun4/core/multiblocks/MultiBlockMachine.java:177]: Okay, I will change it

File: src/main/java/io/github/thebusybiscuit/slimefun4/core/multiblocks/MultiBlockMachine.java [hunk 3]
```diff
@@ -165,6 +168,30 @@ public void load() {
...
+     * @param outputItem
+     *          A crafted {@link ItemStack} from {@link MultiBlockMachine}
+     * @param container
+     *          Our main {@link Container} from {@link MultiBlockMachine}
+     *
+     */
+    @ParametersAreNonnullByDefault
+    protected void handleCraftedItem(ItemStack outputItem, Container container) {
+        Inventory containerInv = container.getInventory();
+        Inventory outputInv = findOutputInventory(outputItem, container.getBlock(), containerInv);
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/core/multiblocks/MultiBlockMachine.java:183]: `Container#getBlock()` is a relatively heavy operation as it does not cache the `Block` internally, whereas we already gotten the `Block` object before-hand, making this completely avoidable.

In other words: This `Block` object should probably be passed via a parameter here to reduce the performance impact of this method.

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/ArmorForge.java [hunk 4]
```diff
@@ -70,9 +70,9 @@ private boolean isCraftable(Inventory inv, ItemStack[] recipe) {
     }
 
     @ParametersAreNonnullByDefault
-    private void craft(Player p, ItemStack output, Inventory inv, Block dispenser) {
+    private void craft(Player p, ItemStack output, Inventory inv, Dispenser dispenser) {
         Inventory fakeInv = createVirtualInventory(inv);
-        Inventory outputInv = findOutputInventory(output, dispenser, inv, fakeInv);
+        Inventory outputInv = findOutputInventory(output, dispenser.getBlock(), inv, fakeInv);
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/ArmorForge.java:75]: Same here, `#getBlock()` is a bit expensive and completely avoidable by just passing the `Block` object via a parameter

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/MagicWorkbench.java [hunk 5]
```diff
@@ -68,9 +68,10 @@ public void onInteract(Player p, Block b) {
         }
     }
 
-    private void craft(Inventory inv, Block dispenser, Player p, Block b, ItemStack output) {
+    @ParametersAreNonnullByDefault
+    private void craft(Inventory inv, Dispenser dispenser, Player p, Block b, ItemStack output) {
         Inventory fakeInv = createVirtualInventory(inv);
-        Inventory outputInv = findOutputInventory(output, dispenser, inv, fakeInv);
+        Inventory outputInv = findOutputInventory(output, dispenser.getBlock(), inv, fakeInv);
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/MagicWorkbench.java:74]: Same here, `#getBlock()` is a bit expensive and completely avoidable by just passing the `Block` object via a parameter

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/MagicWorkbench.java [hunk 6]
```diff
@@ -89,24 +90,23 @@ private void craft(Inventory inv, Block dispenser, Player p, Block b, ItemStack
...
     }
 
-    private void startAnimation(Player p, Block b, Inventory inv, ItemStack output) {
+    private void startAnimation(Player p, Block b, ItemStack output, Dispenser dispenser) {
         for (int j = 0; j < 4; j++) {
             int current = j;
             SlimefunPlugin.runSync(() -> {
                 p.getWorld().playEffect(b.getLocation(), Effect.MOBSPAWNER_FLAMES, 1);
                 p.getWorld().playEffect(b.getLocation(), Effect.ENDER_SIGNAL, 1);
-
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/MagicWorkbench.java:104]: Why was this line removed, can you please put it back?

**Review by TheBusyBiscuit — CHANGES_REQUESTED** [review]
This can be optimized.

Also, thanks for hooking into the new item-spawning system! :)

File: src/main/java/io/github/thebusybiscuit/slimefun4/core/multiblocks/MultiBlockMachine.java [hunk 7]
```diff
@@ -165,6 +171,33 @@ public void load() {
...
+     * @param outputItem
+     *          A crafted {@link ItemStack} from {@link MultiBlockMachine}
+     * @param block
+     *          Main {@link Block} of our {@link Container} from {@link MultiBlockMachine}
+     *
+     */
+    @ParametersAreNonnullByDefault
+    protected void handleCraftedItem(ItemStack outputItem, Block block) {
+        BlockState state = PaperLib.getBlockState(block, false).getState();
+        Validate.isTrue(state instanceof Container);
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/core/multiblocks/MultiBlockMachine.java:186]: Always provide a message alongside `Validate` statements.

File: src/main/java/io/github/thebusybiscuit/slimefun4/core/multiblocks/MultiBlockMachine.java [hunk 8]
```diff
@@ -165,6 +171,33 @@ public void load() {
...
+        Container container = (Container) state;
+        Inventory containerInv = container.getInventory();
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/core/multiblocks/MultiBlockMachine.java:188]: Well, now we have the same paradox as before, getting the BlockState is an expensive operation and we already gotten the BlockState at this point, so this will hurt performance. The BlockState needs to be passed as an argument as much as the Block does.

**Review by TheBusyBiscuit — CHANGES_REQUESTED** [review]

File: src/main/java/io/github/thebusybiscuit/slimefun4/core/multiblocks/MultiBlockMachine.java [hunk 9]
```diff
@@ -165,6 +168,31 @@ public void load() {
...
+        Inventory outputInv = findOutputInventory(outputItem, block, blockInv);
+
+        if (outputInv != null) {
+            outputInv.addItem(outputItem);
+        } else if (InvUtils.fits(blockInv, outputItem)) {
+            blockInv.addItem(outputItem);
+        } else {
+            // fallback
+            SlimefunUtils.spawnItem(block.getLocation(), outputItem, ItemSpawnReason.MULTIBLOCK_MACHINE_OVERFLOW, true);
+        }
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/core/multiblocks/MultiBlockMachine.java:193]: Tiny improvement to improve performance even further, other than this I consider it approved.

```suggestion
        } else {
            ItemStack rest = blockInv.addItem(outputItem).get(0);

            // fallback: drop item
            if (rest != null) {
                SlimefunUtils.spawnItem(block.getLocation(), rest, ItemSpawnReason.MULTIBLOCK_MACHINE_OVERFLOW, true);
            }
        }
```

**Review by TheBusyBiscuit — CHANGES_REQUESTED** [review]

**Review by TheBusyBiscuit — COMMENTED** [review]
LGTM

**Review by TheBusyBiscuit — APPROVED** [review]
I said: LGTM...

**Review by svr333 — APPROVED** [review]
👍🏿
