### PR TITLE
Fix #3701

### LINKED ISSUE #3701: Golden Apple Juice not applied absorption effect
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When drinking ``Golden Apple Juice``, normally will apply Absorption effect, but after drinking it, it is not applied.

### 📑 Reproduction Steps

1. Make a Golden Apple Juice
2. Drink it
3. And look it applied Absorption effect or not

### 💡 Expected Behavior

After drink it, it will apply Absorption effect.

### 📷 Screenshots / Videos

https://user-images.githubusercontent.com/26039249/196673306-69edeea3-4a48-497a-8ece-b5aeb9a5cab1.mp4

### 📜 Server Log

_No response_

### 📂 `/error-reports/` folder

_No response_

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

image

### 🧭 Other plugins

_No response_

### PR DESCRIPTION
**Pull request by tandrew468**
## Description

Drinking Golden Apple Juice gives no absorption effect.

## Proposed changes

Added extra check to account for absorption effect.

## Related Issues (if applicable)

Resolves #3701 

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I have made sure that the proposed changes do not break compatibility across the supported Minecraft versions (1.14.* - 1.19.*).
- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

**Comment by tandrew468** [comment]
POC : 

https://user-images.githubusercontent.com/57212703/197549332-62d4346e-3966-4689-9998-230d897902e1.mp4

**Comment by tandrew468** [comment]
POC: 

https://user-images.githubusercontent.com/57212703/197553221-1d64af86-1cee-4976-85dd-f79feb048fd6.mp4

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/food/Juice.java [hunk 1]
```diff
@@ -68,6 +68,10 @@ public ItemConsumptionHandler getItemHandler() {
                     p.addPotionEffect(effect);
                     break;
                 }
+                else if (effect.getType().equals(PotionEffectType.ABSORPTION)) {
```
Comment (ybw0014) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/food/Juice.java:71]: pretty sure this doesnt fit the coding format.
also u can combine them since the code in the block is the same.

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/food/Juice.java [hunk 2]
```diff
@@ -64,11 +64,7 @@ public ItemConsumptionHandler getItemHandler() {
              * Minecraft has been broken when it comes to Saturation potions for a long time
              */
             for (PotionEffect effect : effects) {
-                if (effect.getType().equals(PotionEffectType.SATURATION)) {
-                    p.addPotionEffect(effect);
-                    break;
-                }
-                else if (effect.getType().equals(PotionEffectType.ABSORPTION)) {
+                if (effect.getType().equals(PotionEffectType.SATURATION) || effect.getType().equals(PotionEffectType.ABSORPTION)) {
```
Comment (WalshyDev) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/food/Juice.java:67]:
```suggestion
                if (effect.getType() == PotionEffectType.SATURATION || effect.getType() == PotionEffectType.ABSORPTION) {
```

**Review by svr333 — APPROVED** [review]

**Review by Sefiraat — APPROVED** [review]
👍
