### PR TITLE
Fix Energy Nets Over&Underflowing

### LINKED ISSUE #3758: Energy regulator resets power level to zero when total power exceeds 2^32 -1
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Once the total power display on the regulator exceeds 2 ^ 32 -1, the power in the network is reset to zero. we need a hard cap to prevent this reset instead of raising the limit.

### 📑 Reproduction Steps

create your power network with an energy regulator
produce enough power to exceed 2.147 billion joules
your network regulator will show no power, then start climbing again

### 💡 Expected Behavior

either the regulator to continue climbing without reset, or set a hard cap and keep the power in the network.

### 📷 Screenshots / Videos

_No response_

### 📜 Server Log

none

### 📂 `/error-reports/` folder

none

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

dev 1041. 

### 🧭 Other plugins

_No response_

### PR DESCRIPTION
**Pull request by JustAHuman-xD**
## Description
As a player it can get really frustrating when all of your energy just gets voided due to overflow and if someone somehow achieves underflow that would be free energy which we do not want.

## Proposed changes
Added NumberUtils#limitedAddition()
Added NumberUtils#flowSafeAddition() and change the corresponding += and -= to use that method

## Related Issues (if applicable)
Resolves #3758

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I have made sure that the proposed changes do not break compatibility across the supported Minecraft versions (1.16.* - 1.19.*).
- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [x] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

**Review by Sfiguz7 — APPROVED** [review]
Reiterating our conversation on Discord, LGTM - if you want to add unit tests please do but I will approve for now

**Comment by JustAHuman-xD** [comment]
I'm going to leave it for now but if someone else feels that I definitely *should* add unit tests I will

**Comment by JustAHuman-xD** [comment]
Here is a photo of both preventions working, as its not a gif you don't *technically* know that it is working but it is
image

File: src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/energy/EnergyNet.java [hunk 1]
```diff
@@ -280,11 +282,29 @@ private int tickAllCapacitors() {
...
+    
+    /**
+     * This detects if 2 integers will overflow/underflow and if they will, returns the corresponding value
+     * @param i1 the first integer
+     * @param i2 the second integer
+     * @return {@link Integer#MAX_VALUE} if overflow detected, {@link Integer#MIN_VALUE} if underflow detected, otherwise the sum of i1 and i2
+     */
+    private int flowSafeAddition(int i1, int i2) {
+        boolean willOverflow = (i1 == Integer.MAX_VALUE && i2 > 0|| i2 == Integer.MAX_VALUE && i1 > 0) || i1 > 0 && i2 > Integer.MAX_VALUE - i1;
+        boolean willUnderflow = (i1 == Integer.MIN_VALUE && i2 < 0|| i2 == Integer.MIN_VALUE && i1 < 0) || i1 < 0 && i2 < Integer.MIN_VALUE - i1;
```
Comment (J3fftw1) [inline src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/energy/EnergyNet.java:299]:
```suggestion
        boolean willOverflow = (i1 == Integer.MAX_VALUE && i2 > 0 || i2 == Integer.MAX_VALUE && i1 > 0) || i1 > 0 && i2 > Integer.MAX_VALUE - i1;
        boolean willUnderflow = (i1 == Integer.MIN_VALUE && i2 < 0 || i2 == Integer.MIN_VALUE && i1 < 0) || i1 < 0 && i2 < Integer.MIN_VALUE - i1;
```

**Review by Sfiguz7 — APPROVED** [review]

File: src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/energy/EnergyNet.java [hunk 2]
```diff
@@ -280,11 +282,29 @@ private int tickAllCapacitors() {
...
+        boolean willOverflow = (i1 == Integer.MAX_VALUE && i2 > 0 || i2 == Integer.MAX_VALUE && i1 > 0) || i1 > 0 && i2 > Integer.MAX_VALUE - i1;
+        boolean willUnderflow = (i1 == Integer.MIN_VALUE && i2 < 0 || i2 == Integer.MIN_VALUE && i1 < 0) || i1 < 0 && i2 < Integer.MIN_VALUE - i1;
+        if (willOverflow) {
+            return Integer.MAX_VALUE;
+        } else if (willUnderflow) {
+            return Integer.MIN_VALUE;
+        } else {
+            return i1 + i2;
+        }
+    }
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/energy/EnergyNet.java:307]: This can probably to go the `NumberUtils` class

File: src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/energy/EnergyNet.java [hunk 3]
```diff
@@ -280,11 +282,29 @@ private int tickAllCapacitors() {
...
         return supply;
     }
+    
+    /**
+     * This detects if 2 integers will overflow/underflow and if they will, returns the corresponding value
+     * @param i1 the first integer
+     * @param i2 the second integer
+     * @return {@link Integer#MAX_VALUE} if overflow detected, {@link Integer#MIN_VALUE} if underflow detected, otherwise the sum of i1 and i2
+     */
+    private int flowSafeAddition(int i1, int i2) {
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/energy/EnergyNet.java:297]: I think `a` and `b` would be better to distinguish the two params.

File: src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/energy/EnergyNet.java (hunk 2 above)
Comment (TheBusyBiscuit) [reply src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/energy/EnergyNet.java:307]: Also to allow a custom limit in the future, could you add `min` and `max` parameters to this method as well as an overload without them where it would just pass `Integer.MAX_VALUE` and `Integer.MIN_VALUE` as defaults?

**Review by TheBusyBiscuit — CHANGES_REQUESTED** [review]
Thanks a lot, a very good and clean addition.
I do have some ideas to make it more future-proof and versatile though.

**Comment by TheBusyBiscuit** [comment]
Also, unit tests for this method would be VERY appropriate in my opinion.

File: src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/energy/EnergyNet.java (hunk 2 above)
Comment (JustAHuman-xD) [reply src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/energy/EnergyNet.java:307]: Ah sure didn't realize we had that class!

File: src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/energy/EnergyNet.java (hunk 3 above)
Comment (JustAHuman-xD) [reply src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/energy/EnergyNet.java:297]: Sure! Wasn't sure which direction I wanted to go 😅

**Comment by JustAHuman-xD** [comment]
There we go, added unit tests and did the refactorings!

File: src/test/java/io/github/thebusybiscuit/slimefun4/utils/TestNumberUtils.java [hunk 4]
```diff
@@ -91,4 +91,29 @@ void testCompactDecimals() {
...
+    void testLimitedAddition() {
+        Assertions.assertEquals(1000, NumberUtils.limitedAddition(1000, 1, 1000, -1000));
+        Assertions.assertEquals(1000, NumberUtils.limitedAddition(1, 1000, 1000, -1000));
+        Assertions.assertEquals(1000, NumberUtils.limitedAddition(999, 2, 1000, -1000));
+        Assertions.assertEquals(1000, NumberUtils.limitedAddition(2, 999, 1000, -1000));
+        Assertions.assertEquals(-1000, NumberUtils.limitedAddition(-1000, -1, 1000, -1000));
+        Assertions.assertEquals(-1000, NumberUtils.limitedAddition(-1, -1000, 1000, -1000));
+        Assertions.assertEquals(-1000, NumberUtils.limitedAddition(-999, -2, 1000, -1000));
+        Assertions.assertEquals(-1000, NumberUtils.limitedAddition(-2, -999, 1000, -1000));
+    }
```
Comment (TheBusyBiscuit) [inline src/test/java/io/github/thebusybiscuit/slimefun4/utils/TestNumberUtils.java:118]: This basically cries for a `CsvSource` input. But then again, we always did it this way thus far so why change now XD

Does this cover all possible cases for full coverage?

Comment (JustAHuman-xD) [reply src/test/java/io/github/thebusybiscuit/slimefun4/utils/TestNumberUtils.java:118]: It should cover all cases, I just went through the 2 booleans and did the calls that would set whichever parts of it to be true

File: src/main/java/io/github/thebusybiscuit/slimefun4/utils/NumberUtils.java [hunk 5]
```diff
@@ -281,4 +281,34 @@ public static int getJavaVersion() {
...
+    public static int limitedAddition(int a, int b, int max, int min) {
+        boolean willOverflow = (a == max && b > 0 || b == max && a > 0) || a > 0 && b > max - a;
+        boolean willUnderflow = (a == min && b < 0 || b == min && a < 0) || a < 0 && b < min - a;
+        if (willOverflow) {
+            return max;
+        } else if (willUnderflow) {
+            return min;
+        } else {
+            return a + b;
+        }
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/utils/NumberUtils.java:312]: `willUnderflow` won't need to be computed if `willOverflow` is already `true`.

```suggestion
        boolean willOverflow = (a == max && b > 0 || b == max && a > 0) || a > 0 && b > max - a;

        if (willOverflow) {
            return max;
        }

        boolean willUnderflow = (a == min && b < 0 || b == min && a < 0) || a < 0 && b < min - a;

        if (willUnderflow) {
            return min;
        } else {
            return a + b;
        }
```

File: src/test/java/io/github/thebusybiscuit/slimefun4/utils/TestNumberUtils.java (hunk 4 above)
Comment (JustAHuman-xD) [reply src/test/java/io/github/thebusybiscuit/slimefun4/utils/TestNumberUtils.java:118]: Also ngl don't know what a csvSource is

File: src/main/java/io/github/thebusybiscuit/slimefun4/utils/NumberUtils.java [hunk 6]
```diff
@@ -281,4 +281,34 @@ public static int getJavaVersion() {
...
+    
+    /**
+     * This detects if 2 integers will overflow/underflow past a maximum or minimum value and if they will, returns the corresponding value
+     * @param a the first integer
+     * @param b the second integer
+     * @param max the maximum value for the operation
+     * @param min the minimum value for the operation
+     * @return max if overflow detected, min if underflow detected, otherwise the sum of a and b
+     */
+    public static int limitedAddition(int a, int b, int max, int min) {
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/utils/NumberUtils.java:303]: Some voice inside my head wants `min` to come before `max`.

```suggestion
     * @param min the minimum value for the operation
     * @param max the maximum value for the operation
     * @return max if overflow detected, min if underflow detected, otherwise the sum of a and b
     */
    public static int limitedAddition(int a, int b, int min, int max) {
```

**Review by TheBusyBiscuit — CHANGES_REQUESTED** [review]

File: src/main/java/io/github/thebusybiscuit/slimefun4/utils/NumberUtils.java (hunk 5 above)
Comment (JustAHuman-xD) [reply src/main/java/io/github/thebusybiscuit/slimefun4/utils/NumberUtils.java:312]: Good point

File: src/test/java/io/github/thebusybiscuit/slimefun4/utils/TestNumberUtils.java (hunk 4 above)
Comment (TheBusyBiscuit) [reply src/test/java/io/github/thebusybiscuit/slimefun4/utils/TestNumberUtils.java:118]: Me neither.

*Just kidding*, it's one way to insert lots of different parameters into parameterized tests by formatting the data like a .csv file. But it's not needed here at all, we never go that fancy.

File: src/main/java/io/github/thebusybiscuit/slimefun4/utils/NumberUtils.java (hunk 6 above)
Comment (JustAHuman-xD) [reply src/main/java/io/github/thebusybiscuit/slimefun4/utils/NumberUtils.java:303]: Now that you say that I 100% agree

**Comment by JustAHuman-xD** [comment]
I'll quickly do the switch between min and max, I'll just need to flip the params in the tests and flow safe method aswell

**Review by TheBusyBiscuit — APPROVED** [review]
LGTM

**Review by Sfiguz7 — APPROVED** [review]
Oh hey tests! Thank you JustACliffhanger :)
