### PR TITLE
Possibly fixes #2296.

### LINKED ISSUE #2296: Pickaxe Of Vein Mining doesn't works with Silk Touch
## Description (REQUIRED)

When you use a silktouch pickaxe of vein mining, trying to dig diamond ores, it will drops you diamond but not the diamond ores. It can perfectlly works with fortune but not the silktouch. 

Pickaxe of Vein Mining doesn't work well with silktouch_2

Plugin Version:
Slimefun Version

## Steps to reproduce the Issue (REQUIRED)

1. Give yourselve a Pickaxe of Vein Mining.
2. Enchant the pickaxe with Silktouch.
3. Dig some ores and you'll see.

## Expected behavior (REQUIRED)

Let Silktouch works well with Pickaxe of Vein Minning.

## Environment (REQUIRED)

 - Server Software (Spigot/Paper):Paper
 - Minecraft Version:1.16.2
 - Slimefun Version:vDev - 665
 - CS-CoreLib Version:vDev -79

### PR DESCRIPTION
**Pull request by LinoxGH**
## Description

Added a check for silk touch to Pickaxe of Vein Mining.

## Related Issues

Fixes #2296 

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [X] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.
Note: The changes aren't tested and were made on a mobile phone.

### CODE REVIEW

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/PickaxeOfVeinMining.java [hunk 1]
```diff
@@ -60,9 +61,15 @@ private void breakBlocks(Player p, List<Block> blocks, int fortune) {
         for (Block b : blocks) {
             if (SlimefunPlugin.getProtectionManager().hasPermission(p, b.getLocation(), ProtectableAction.BREAK_BLOCK)) {
                 b.getWorld().playEffect(b.getLocation(), Effect.STEP_SOUND, b.getType());
+                
+                if (getItem().containsEnchantment(Enchantment.SILK_TOUCH)) {
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/PickaxeOfVeinMining.java:65]: getItem() will return the original SlimefunItemStack, not the currently used item!

**Review by TheBusyBiscuit — CHANGES_REQUESTED** [review]

**Review by TheBusyBiscuit — APPROVED** [review]
