### PR TITLE
Fixes #2647

### LINKED ISSUE #2647: Boots of Stomper work on NPCs
## :round_pushpin: Description (REQUIRED)

The boots of stomper can move NPC's in claimed area like spawn.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

Fly up land and it moves the NPC's
I tested with op and no op and both move them
https://imgur.com/a/snIJYOw

## :bulb: Expected behavior (REQUIRED)

Not to move the NPC's when landing

## :scroll: Server Log

N/a

## :open_file_folder: /error-reports/ Folder

N/a

## :compass: Environment (REQUIRED)

 - Server Software: 
 - Minecraft Version: 
 - Slimefun Version: 
 - CS-CoreLib Version: 
https://imgur.com/a/snIJYOw

### PR DESCRIPTION
**Pull request by WalshyDev**
## Description
Add some more checks in order to make this more valid. This will resolve a lot of conflicts with other plugins. This has been confirmed fix with Citizens

## Changes
Check #isCollidable and #hasGravity

## Related Issues
Resolves #2647 

## Checklist
- [X] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/armor/StomperBoots.java [hunk 1]
```diff
@@ -47,7 +47,12 @@ public void stomp(EntityDamageEvent fallDamageEvent) {
         p.setVelocity(new Vector(0, 0.7, 0));
 
         for (Entity n : p.getNearbyEntities(4, 4, 4)) {
-            if (n instanceof LivingEntity && n.isValid() && !n.getUniqueId().equals(p.getUniqueId())) {
+            if (n instanceof LivingEntity
+                && n.isValid()
+                && !n.getUniqueId().equals(p.getUniqueId())
+                && ((LivingEntity) n).isCollidable()
+                && n.hasGravity()
+            ) {
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/armor/StomperBoots.java:55]: I think this unholy abomination of new lines justifies to have its own dedicated method.

**Review by TheBusyBiscuit — CHANGES_REQUESTED** [review]

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/armor/StomperBoots.java (hunk 1 above)
Comment (WalshyDev) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/armor/StomperBoots.java:55]: "abomination"

you seen a few lines down? 181 chars on a line monkaS

Comment (TheBusyBiscuit) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/armor/StomperBoots.java:55]: Still, putting this statement into its own method would also allow for flexibility in case a sub implementation wants to add additional checks.

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/armor/StomperBoots.java [hunk 2]
```diff
@@ -37,54 +39,49 @@ public StomperBoots(Category category, SlimefunItemStack item, RecipeType recipe
...
+                        ((LivingEntity) entity).damage(event.getDamage());
                     }
                 }
             }
         }
 
         for (BlockFace face : BlockFace.values()) {
-            Block b = p.getLocation().getBlock().getRelative(BlockFace.DOWN).getRelative(face);
-            p.getWorld().playEffect(b.getLocation(), Effect.STEP_SOUND, b.getType());
+            Block b = player.getLocation().getBlock().getRelative(BlockFace.DOWN).getRelative(face);
```
Comment (J3fftw1) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/armor/StomperBoots.java:69]: changes p to player but b not to block?

Comment (WalshyDev) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/armor/StomperBoots.java:69]: reeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee leave me alone. Was just changing the shit associated with my method. Also `b` is a bit clearer than `n` or `p`

Comment (J3fftw1) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/armor/StomperBoots.java:69]: i mean b is as clear as p in this case i agree n is weird but b and p are both really clear in this case so i would say make them all full name or 1 letter be consistent

**Review by svr333 — APPROVED** [review]
Looks good

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/armor/StomperBoots.java [hunk 3]
```diff
@@ -89,4 +91,20 @@ private Vector getShockwave(Location origin, Location target) {
         }
     }
 
+    /**
+     * Checks if the stomper boots can move an entity and is not the player who is using the boots.
+     * <br><b>For developers:</b> If you're spawning an immovable NPC, you should be denying
+     * collision with {@code LivingEntity#setCollidable(false)} or
+     * gravity with {@code LivingEntity#setGravity(false)}.
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/armor/StomperBoots.java:98]: Why are you using `@code` instead of `@link` here?

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/armor/StomperBoots.java [hunk 4]
```diff
@@ -89,4 +91,20 @@ private Vector getShockwave(Location origin, Location target) {
...
+     *
+     * @param entity
+     *            The {@link LivingEntity} to check.
+     * @param player
+     *            The {@link Player} using the {@link StomperBoots}.
+     * @return If the entity can move.
+     */
+    private boolean canMoveEntity(@Nonnull LivingEntity entity, @Nonnull Player player) {
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/armor/StomperBoots.java:106]: I would suggest to swap the order of parameters here and rename the method.
The current order is unintuitive in my opinion or at least in a grammatical sense. If the method was called "canBePushedBy" then the current order would make more sense. So I am in favour of swapping these here.

Also if you want this to be overridden, then it should be at least `protected`.

```suggestion
    protected boolean canPush(@Nonnull Player player, @Nonnull LivingEntity entity) {
```

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/armor/StomperBoots.java [hunk 5]
```diff
@@ -89,4 +91,20 @@ private Vector getShockwave(Location origin, Location target) {
         }
     }
 
+    /**
+     * Checks if the stomper boots can move an entity and is not the player who is using the boots.
+     * <br><b>For developers:</b> If you're spawning an immovable NPC, you should be denying
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/armor/StomperBoots.java:96]: According to the javadocs convention `<br>` should not be used. Instead `<p>` should be used to start a new paragraph.
Although you will see the line break quite often in this codebase already because I didn't know that until recently either.

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/armor/StomperBoots.java [hunk 6]
```diff
@@ -37,49 +39,49 @@ public StomperBoots(Category category, SlimefunItemStack item, RecipeType recipe
...
                 }
             }
         }
 
         for (BlockFace face : BlockFace.values()) {
-            Block b = p.getLocation().getBlock().getRelative(BlockFace.DOWN).getRelative(face);
-            p.getWorld().playEffect(b.getLocation(), Effect.STEP_SOUND, b.getType());
+            Block block = player.getLocation().getBlock().getRelative(BlockFace.DOWN).getRelative(face);
+            player.getWorld().playEffect(block.getLocation(), Effect.STEP_SOUND, block.getType());
         }
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/armor/StomperBoots.java:71]: I don't really see much of a problem with the naming of p, n and b but sure.

**Review by TheBusyBiscuit — CHANGES_REQUESTED** [review]
A few nitpicky convention type of things and a mistake in the access modifier. Otherwise looking good.

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/armor/StomperBoots.java (hunk 6 above)
Comment (svr333) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/armor/StomperBoots.java:71]: p and b could be used fine like that but n for entity is a bit odd here, and besides I think using full names is cleaner and more easily readable

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/armor/StomperBoots.java (hunk 3 above)
Comment (WalshyDev) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/armor/StomperBoots.java:98]: Just for the sake of adding `false` to be clear what people should do. I can change it

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/armor/StomperBoots.java (hunk 5 above)
Comment (WalshyDev) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/armor/StomperBoots.java:96]: Was doing it for consistency but sute

**Review by svr333 — APPROVED** [review]

**Review by TheBusyBiscuit — APPROVED** [review]
