### PR TITLE
Fixes #3206

### LINKED ISSUE #3206: NoSuchMethodError: org.bukkit.inventory.Inventory.isEmpty()Z
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When I attempted to do a craft with a enhanced crafting table, the exception happened.

### 📑 Reproduction Steps

1. Build a enhanced crafting table.
2. Attempt to do a craft.

### 💡 Expected Behavior

I expected that no exception would happen, and when the enhanced crafting table was empty it would notice the player that no recipe was matched. 

### 📷 Screenshots / Videos

_No response_

### 📜 Server Log

https://pastebin.com/8mi9HgZr

### 📂 `/error-reports/` folder

_No response_

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.15.x

### ⭐ Slimefun version

Slimefun vDEV - 961 (git e187d878)

### 🧭 Other plugins

_No response_

### PR DESCRIPTION
**Pull request by WalshyDev**
## Description
Spigot 1.16 introduced Inventory#isEmpty. Since we support 1.14 and 1.15 we don't want to call this on those versions. This introduces a small util method and fixes a place where Inventory#isEmpty was called.

## Proposed changes
This introduces a small util method and fixes a place where Inventory#isEmpty was called.

## Related Issues (if applicable)
Resolves #3206 

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

**Review by Sfiguz7 — APPROVED** [review]

**Review by svr333 — APPROVED** [review]

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/EnhancedCraftingTable.java [hunk 1]
```diff
@@ -53,7 +53,7 @@ public void onInteract(Player p, Block b) {
                 }
             }
 
-            if (inv.isEmpty()) {
+            if (SlimefunUtils.isInventoryEmpty(inv)) {
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/EnhancedCraftingTable.java:56]: There is more than one machine in Slimefun, this only fixes it for the Enhanced Crafting Table.
At least two more cases just by text search alone...

https://github.com/Slimefun/Slimefun4/blob/8c0ef8a97fbb289310c3f9aacf26ca6c76be8867/src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/MagicWorkbench.java#L63

https://github.com/Slimefun/Slimefun4/blob/8c0ef8a97fbb289310c3f9aacf26ca6c76be8867/src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/ArmorForge.java#L54

Come on, guys...

@svr333 @Sfiguz7 Did you actually review this or just blindly approve because Walshy told you to? :eyes:

**Comment by WalshyDev** [comment]
I didn't find any in search REEEE, thanks Cookie

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/EnhancedCraftingTable.java (hunk 1 above)
Comment (svr333) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/EnhancedCraftingTable.java:56]: I reviewed the code that changed on this one I didn't check for other places where this might need an implementation  
my bad
