### PR TITLE
fix getting radiated when not supposed to

### LINKED ISSUE #3945: i get harmed since the new radiation update
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Hello, since a few days each time i login from the /hub to the   survival server, i get radiated. my countdown get less and less and i guess at one point i will die. but: i dont have any blistering, uranium, neptunium, plutonium in inventory, i dont run any nuclear reactors. i wear infinity gear. i also tested it to change gear to a new craftet hazmaz suite... i still  get radiated....

### 📑 Reproduction Steps

i dont know how to reproduce this.

i am only a player on the server, so no admin or stuff or developer. i cant provide any more data.

### 💡 Expected Behavior

i am only a player on the server, so no admin or stuff or developer. i cant provide any more data.

### 📷 Screenshots / Videos

47v

https://github.com/Slimefun/Slimefun4/assets/142180177/ec1ce64e-506a-42e1-bfb9-4e525c9b229e

### 📜 Server Log

_No response_

### 📂 `/error-reports/` folder

_No response_

### 💻 Server Software

Spigot

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

00000.0

### 🧭 Other plugins

i am only a player on the server, so no admin or stuff or developer. i cant provide any more data.

### PR DESCRIPTION
**Pull request by iTwins**
## Description

There were 3 cases where you would get radiated when you weren't supposed to. The first case was when joining and having radioactive materials in your inventory. The radiation task would run before the armor task, meaning the radiation task would think you weren't wearing protective gear. The second case was ``hasFullProtectionAgainst`` returning false is some cases where it was supposed to return true. Example: infinity leggings with hazmat boots. The third case was when you were exposed to radiation, then put on protective armor, the exposure would stay. Meaning that when you would take your armor of you would get radiated again, even if you hadn't had radioactive materials in your inventory for a while.

## Proposed changes

1. Cache armor on join
2. Rewrite ``hasFullProtectionAgainst`` to actually work correctly in all cases.
3. Decay exposure when fully protected

## Related Issues (if applicable)

Resolves #3945

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I have made sure that the proposed changes do not break compatibility across the supported Minecraft versions (1.16.* - 1.20.*).
- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/JoinListener.java [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+            final ItemStack[] armorContents = e.getPlayer().getInventory().getArmorContents();
+            final HashedArmorpiece[] hashedArmorpieces = playerProfile.getArmor();
+            for (int i = 0; i < 4; i++) {
+                if (armorContents[i] != null && armorContents[i].getType() != Material.AIR && SlimefunItem.getByItem(armorContents[i]) instanceof SlimefunArmorPiece sfArmorPiece) {
+                    hashedArmorpieces[i].update(armorContents[i], sfArmorPiece);
+                }
+            }
+        });
+    }
+
```
Comment (JustAHuman-xD) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/JoinListener.java:42]:
```suggestion
```

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/JoinListener.java [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+        plugin.getServer().getPluginManager().registerEvents(this, plugin);
+    }
+
+    @EventHandler
+    public void onJoin(@Nonnull PlayerJoinEvent e) {
+        PlayerProfile.get(e.getPlayer(), playerProfile -> {
+            final ItemStack[] armorContents = e.getPlayer().getInventory().getArmorContents();
+            final HashedArmorpiece[] hashedArmorpieces = playerProfile.getArmor();
+            for (int i = 0; i < 4; i++) {
+                if (armorContents[i] != null && armorContents[i].getType() != Material.AIR && SlimefunItem.getByItem(armorContents[i]) instanceof SlimefunArmorPiece sfArmorPiece) {
```
Comment (JustAHuman-xD) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/JoinListener.java:36]: Maybe assign armorContents[i] to a variable since it's used repeatedly

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/JoinListener.java (hunk 1 above)
Comment (iTwins) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/JoinListener.java:42]: In my opinion it's better with an extra empty line between last method and closing bracket of the class.

**Review by J3fftw1 — APPROVED** [review]
LGTM
I dont mind the empty line

**Review by JustAHuman-xD — APPROVED** [review]
LGTM!
