### PR TITLE
Filter unlocked researches of player

### LINKED ISSUE #3995: Command /sf stats doesnt work in some cases
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Some of the items cant be disabled because then when you unlock every single reasearch its giving an error after using command /sf stats.

### 📑 Reproduction Steps

1. Disable particular items in items.yml
   (For example disable every single piece of REINFORCED ALLOY armor.)
2. Give yourself all the researches.
3. Run command /sf stats,

### 💡 Expected Behavior

It should show stats as normal without error.

### 📷 Screenshots / Videos

image

### 📜 Server Log

https://pastebin.com/H6K4Cp7C

### 📂 `/error-reports/` folder

_No response_

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

Paper git-Paper-233 (MC: 1.20.2)
Slimefun DEV - 1104 (git c977454e)
Metrics-Module #29
Java 17
 
Installed Addons: (12)
Networks vDEV - 50 (git 3de3c9d6)
InfinityExpansion vDEV - 144 (git 9da37202)
AureliumSkills vBeta 1.3.23
ShopGUIPlus v1.92.0
LiteXpansion vDEV - 192 (git 661862ed)
IllegalStack v2.9.8
aquacore v1.4-SNAPSHOT
Residence v5.1.3.0
CMI v9.6.5.3
FluffyMachines vDEV - 132 (git ccf029ba)
ItemsAdder v3.6.0
HeadLimiter vDEV - 15 (git 66d18f52)

### 🧭 Other plugins

_No response_

### PR DESCRIPTION
**Pull request by iTwins**
## Description

When you first researched an item then disabled it you would still have the research. Sf stats however doesn't count researches without any enabled items for the total amount of researches. This means you could have more researches unlocked then the 'total'. This resulted in a fraction >1, thus an index >= titels.size, thus throwing an ``IndexOutOfBounds`` exception.

## Proposed changes

Also filter the unlocked researches of the player to only include researches with at least 1 enabled item.

## Related Issues (if applicable)

Resolved #3995

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I have made sure that the proposed changes do not break compatibility across the supported Minecraft versions (1.16.* - 1.20.*).
- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

File: src/main/java/io/github/thebusybiscuit/slimefun4/api/player/PlayerProfile.java [hunk 1]
```diff
@@ -325,35 +325,52 @@ public final void markDirty() {
...
+     * and total xp spent.
+     *
+     * @param sender The {@link CommandSender} for which to get the statistics and send them to.
+     */
     public void sendStats(@Nonnull CommandSender sender) {
-        Set<Research> unlockedResearches = getResearches();
-        int levels = unlockedResearches.stream().mapToInt(Research::getCost).sum();
-        int allResearches = nonEmptyResearches();
+        int unlockedResearches = countNonEmptyResearches(getResearches());
+        int levels = getResearches().stream().mapToInt(Research::getCost).sum();
```
Comment (JustAHuman-xD) [inline src/main/java/io/github/thebusybiscuit/slimefun4/api/player/PlayerProfile.java:364]: Any reason you left this as all researches regardless of enabled?

Comment (iTwins) [reply src/main/java/io/github/thebusybiscuit/slimefun4/api/player/PlayerProfile.java:364]: well I figured that the player did spend the levels, so they should be counted.

**Review by TheBusyBiscuit — APPROVED** [review]
LGTM 👍🏻 Very nice

**Review by JustAHuman-xD — APPROVED** [review]
LGTM
