### PR TITLE
Fix #3361

### LINKED ISSUE #3361: Soulbound not disabled when disabled in config
### ❗ Checklist

- [x] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When I disabled soulbound items in the config already soulbound enchanted items from the ancient rune still functioned. No other config option exists for disabling already soulbound enchanted items.

### 📑 Reproduction Steps

1. Have ancient rune of soulbind enabled
2. Drop the rune with a piece of armor to enchant it
3. Disable the rune
4. Use the soulbound item

### 💡 Expected Behavior

Expected behaviour would be the soulbounded item would not function just like any SF item that is disabled.

### 📷 Screenshots / Videos

https://discord.com/channels/565557184348422174/565569972697301020/914758306130706442 <-- Related convo in the SF discord

### 📜 Server Log

Nothing in Logs

### 📂 `/error-reports/` folder

No errors

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.17.x

### ⭐ Slimefun version

Versions

### 🧭 Other plugins

_No response_

### PR DESCRIPTION
**Pull request by JustAHuman-xD**
## Description
When a Item is soulbound via the Soulbound Rune it will still act as soulbound when the rune is disabled. However if someone crafts for example, a soulbound axe it will only act as soulbound if the axe is not disabled. This makes the item only act as soulbound if the rune is not disabled.

## Proposed changes
Added a reference to the soulbound rune slimefun item
Check if it is not null, not disabled, and not disabled in the specific world

## Related Issues (if applicable)
Resolves #3361 

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I have made sure that the proposed changes do not break compatibility across the supported Minecraft versions (1.16.* - 1.19.*).
- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [x] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

File: src/main/java/io/github/thebusybiscuit/slimefun4/utils/SlimefunUtils.java [hunk 1]
```diff
@@ -120,7 +123,8 @@ public static boolean isSoulbound(@Nullable ItemStack item, @Nullable World worl
         if (item != null && item.getType() != Material.AIR) {
             ItemMeta meta = item.hasItemMeta() ? item.getItemMeta() : null;
 
-            if (hasSoulboundFlag(meta)) {
+            SlimefunItem rune = SlimefunItems.SOULBOUND_RUNE.getItem();
+            if (hasSoulboundFlag(meta) && rune != null && !rune.isDisabled() && (world == null || !rune.isDisabledIn(world))) {
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/utils/SlimefunUtils.java:127]: This should probably be nested inside the if-statement. If the flag is not present then there is no need to perform any additional checks.

Or a much better approach would be to put the `hasSoulboundFlag` at the end. Since it might be more expensive computation-wise. Depends on what the cheaper operation is. The null check and `.isDisabled()` are probably the cheapest ones. So let's try it that way I guess. This should allow the code to disregard unneeded operations

```suggestion
            SlimefunItem rune = SlimefunItems.SOULBOUND_RUNE.getItem();
            if (rune != null && !rune.isDisabled() && (world == null || !rune.isDisabledIn(world)) && hasSoulboundFlag(meta)) {
```

**Review by TheBusyBiscuit — CHANGES_REQUESTED** [review]

**Comment by JustAHuman-xD** [comment]
Yeah I was wondering which would be cheaper, wasn't sure.

File: src/main/java/io/github/thebusybiscuit/slimefun4/utils/SlimefunUtils.java [hunk 2]
```diff
@@ -11,6 +11,7 @@
 import javax.annotation.Nullable;
 import javax.annotation.ParametersAreNonnullByDefault;
 
+import io.github.thebusybiscuit.slimefun4.implementation.SlimefunItems;
```
Comment (Sefiraat) [inline src/main/java/io/github/thebusybiscuit/slimefun4/utils/SlimefunUtils.java:14]: This import needs to be moved to order correctly :)

**Review by Sefiraat — CHANGES_REQUESTED** [review]

File: src/main/java/io/github/thebusybiscuit/slimefun4/utils/SlimefunUtils.java (hunk 2 above)
Comment (JustAHuman-xD) [reply src/main/java/io/github/thebusybiscuit/slimefun4/utils/SlimefunUtils.java]: Fixed!

**Review by Sefiraat — APPROVED** [review]
👍

**Review by svr333 — APPROVED** [review]

**Review by TheBusyBiscuit — APPROVED** [review]
LGTM
