### PR TITLE
Fixes #2903

### LINKED ISSUE #2903: Crucibles when next to each other don't make lava
## :round_pushpin: Description (REQUIRED)

When you activate multiple crucibles beside each other they try to make lava but it cancels out and you get nothing

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Get 2 or more crucibles
2. Place them directly beside each other
3. Activate them with cobblestone to begin the lava making process
https://youtu.be/JoOVaRbo5lw
## :bulb: Expected behavior (REQUIRED)

Continue to make lava until it's finished, then the lava remains there flowing out if there's nothing to contain it.

## :scroll: Server Log

N/A

## :open_file_folder: /error-reports/ Folder

N/A

## :compass: Environment (REQUIRED)

 - Server Software: Purpur
 - Minecraft Version: 1.16.5
 - Slimefun Version: DEV 850

### PR DESCRIPTION
**Pull request by RobotHanzo**
## Description
Fixed the bug in #2903 where crucibles next to each other doesnt work due to the output updating each other causing the liquid to be updated.

## Changes
Made applyPhysics false when running block.setType

## Related Issues
Fixes #2903 

## Checklist
- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/blocks/Crucible.java [hunk 1]
```diff
@@ -14,6 +14,7 @@
 import org.bukkit.World.Environment;
 import org.bukkit.block.Block;
 import org.bukkit.block.BlockFace;
+import org.bukkit.block.data.BlockData;
```
Comment (WalshyDev) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/blocks/Crucible.java:17]: Unused import

**Review by WalshyDev — DISMISSED** [review]

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/blocks/Crucible.java (hunk 1 above)
Comment (RobotHanzo) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/blocks/Crucible.java]: Fixed, forgot to remove after experimentations

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/blocks/Crucible.java [hunk 2]
```diff
@@ -188,7 +188,7 @@ private void addLiquidLevel(@Nonnull Block block, boolean water) {
 
     private void placeLiquid(@Nonnull Block block, boolean water) {
         if (block.getType() == Material.AIR || block.getType() == Material.CAVE_AIR || block.getType() == Material.VOID_AIR) {
-            block.setType(water ? Material.WATER : Material.LAVA);
+            block.setType(water ? Material.WATER : Material.LAVA, false);
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/blocks/Crucible.java:191]: Changes like these should usually be preceded by a comment explaining them with a reference to the issue.
Example:

```suggestion
            // Fixes #2903 - Cancel physics update to resolve weird overlapping
            block.setType(water ? Material.WATER : Material.LAVA, false);
```

**Review by TheBusyBiscuit — CHANGES_REQUESTED** [review]
One minor addition I would like to suggest to make it future-proof and transparent, otherwise looking good.

Did you ensure that this does indeed fix the corresponding issue?

**Review by TheBusyBiscuit — APPROVED** [review]
Lgtm if this was well tested.

**Comment by RobotHanzo** [comment]
It is tested, forgot to include a demonstration video since it was a small PR
[YouTube](https://youtu.be/Ib1LvNlp_N4)

**Comment by TheBusyBiscuit** [comment]
Perfect! Now we just need to wait for a second reviewer.

**Review by WalshyDev — APPROVED** [review]
