### PR TITLE
Fix sensitive blocks attached to sf blocks not dropping (1.19+)

### LINKED ISSUE #3182: Block Placer makes blocks vanish
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When placing a block, which needs to be supported (eg: Redstone Dust, Repeater, Redstone Torch) on top of a Block Placer, when the Block Placer is broken, the block on top does not drop into item form.

I only checked with Redstone Dust, Repeaters, and Redstone Torches.
I broke the block placer first using a Netherite Pickaxe, only with Vanilla Enchants

### 📑 Reproduction Steps

1. Place a Block Placer
2. Place Any of the following on top of Block Placer
    - Redstone Dust
    - Redstone Repeater
    - Redstone Torch
3. Break the Block Placer

### 💡 Expected Behavior

When the Block Placer is broken, the block on top is expected to drop as an Item, which it does not.

### 📜 Server Log

_No response_

### 📂 `/error-reports/` folder

_No response_

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.17.x

### ⭐ Slimefun version

Slimefun DEV - 956

[Screenshot of Version](https://gyazo.com/815101758121ba1a5973b98ed00e90f8)

### 🧭 Other plugins

_No response_

### LINKED ISSUE #3831: Signs attached to custom blocks don't drop
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When placing a sign on an output chest or edged/reinforced furnace. if you subsequently break the block the sign will not drop.

### 📑 Reproduction Steps

1. Place down an output chest
2. Place a sign on it
3. Break the output chest

### 💡 Expected Behavior

I expect the sign to drop.

### 📷 Screenshots / Videos

_No response_

### 📜 Server Log

_No response_

### 📂 `/error-reports/` folder

_No response_

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

DEV 1050

### 🧭 Other plugins

_No response_

### PR DESCRIPTION
**Pull request by iTwins**
## Description

When you would break a Slimefun block any sensitive blocks attached to it would be destroyed, but not drop their item.
This fix only works for 1.19+, but that accounts for 4/5 of all Slimefun servers. Feel free to suggest a 1.16-1.18 version.

## Proposed changes

Recursively check all attached sensitive blocks and drop them if they should be, while respecting ``max-chained-neighbor-updates`` in ``server.properties``.

## Related Issues (if applicable)

Resolves #3182 
Resolves #3831 

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I have made sure that the proposed changes do not break compatibility across the supported Minecraft versions (1.16.* - 1.20.*).
- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

**Review by J3fftw1 — COMMENTED** [review]
Won’t this create a ghost block if the sensitive block is a Slimefun block?

**Comment by iTwins** [comment]
If it does now then it already did before this change. The only extra thing I do now is drop the items of sensitive blocks that get destroyed. Also the only 2 sensitive blocks in Slimefun are the elevator plate and teleportation matrix activator and those get handled by ``checkForSensitiveBlockAbove`` before my method runs.

This new method could server as the more inclusive replacement for ``checkForSensitiveBlockAbove`` if I check blockstorage for each of the destroyed blocks, but before that's possible the 1.16-1.18 fix has to be implemented.

File: src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockListener.java [hunk 1]
```diff
@@ -222,6 +229,53 @@ private void dropItems(BlockBreakEvent e, List<ItemStack> drops) {
...
+     *      The {@link Block} the {@link BlockData} would be at
+     * @return
+     *      Whether the {@link BlockData} would be supported at the given {@link Block}
+     */
+    @ParametersAreNonnullByDefault
+    private boolean isSupported(BlockData blockData, Block block) {
+        if (Slimefun.getMinecraftVersion().isAtLeast(MinecraftVersion.MINECRAFT_1_19)) {
+            return blockData.isSupported(block);
+        } else {
+            // TODO: Make 1.16-1.18 version. BlockData::isSupported is 1.19+.
```
Comment (J3fftw1) [inline src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockListener.java:274]: is this todo for this PR or later?

Comment (iTwins) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockListener.java:274]: I wasn't planning on making that in this pr and I doubt anyone else will, so worst case scenario this is a fix for only 1.19+ and the version check can be removed when we drop support for 1.18.

Comment (J3fftw1) [reply src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/BlockListener.java:274]: Im fine with that. We then have solved the issue for over 75% of the servers atleast

**Review by J3fftw1 — APPROVED** [review]

**Review by variananora — APPROVED** [review]
LGTM, build test passed. Tested on Paper 1.19.4-550 and Paper 1.20.2-318

**Review by Sfiguz7 — APPROVED** [review]
